import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	// Obsidian installs only main.js/manifest.json/styles.css, so the embedding
	// runtime (@huggingface/transformers) has to be INSIDE main.js — it can't ship
	// as a sibling file. Bundling it is only possible on the browser platform: the
	// package's exports map routes `node` to onnxruntime-node, whose prebuilt
	// *.node binaries esbuild cannot load ("No loader is configured for '.node'").
	// The browser condition resolves to dist/transformers.web.js -> onnxruntime-web,
	// which is pure JS + a WASM asset, and adds ~800 KB to the bundle (T039).
	//
	// The WASM asset itself (ort-wasm-simd-threaded.jsep.wasm, ~20 MB) still cannot
	// be bundled; it is fetched alongside the model into the plugin folder and
	// pointed at via env.backends.onnx.wasm.wasmPaths at runtime.
	platform: 'browser',
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
