// Generated by /spec-test for specs/001-core-data-models/spec.md
// Verifies the current src/models implementation against the spec's
// Acceptance Scenarios and Success Criteria. Run via esbuild + node
// (the repo's no-test-runner convention). Report-only.

import { isValidSubscription, assignCheckInterval } from '../../src/models/subscription';
import type { Subscription } from '../../src/models/subscription';
import { isValidPaper, toPaper, isPaperSourceId } from '../../src/models/paper';
import type { PaperCandidate, Paper } from '../../src/models/paper';
import { isValidPluginSettings, DEFAULT_PLUGIN_SETTINGS } from '../../src/models/settings';

type Status = 'PASS' | 'FAIL' | 'SKIP';
interface Result {
	id: string;
	desc: string;
	status: Status;
	note?: string;
}

const results: Result[] = [];

function check(id: string, desc: string, fn: () => void): void {
	try {
		fn();
		results.push({ id, desc, status: 'PASS' });
	} catch (e) {
		results.push({ id, desc, status: 'FAIL', note: (e as Error).message });
	}
}

function skip(id: string, desc: string, reason: string): void {
	results.push({ id, desc, status: 'SKIP', note: reason });
}

function assert(cond: boolean, msg: string): void {
	if (!cond) {
		throw new Error(msg);
	}
}

// ---- Fixtures -------------------------------------------------------------

const validSub = (type: string): Subscription => ({
	type: type as Subscription['type'],
	value: 'transformers',
	label: 'Transformers',
	checkIntervalHours: 24,
	lastCheckedAt: null,
	enabled: true,
});

const validPaper = (): Paper => ({
	title: 'Attention Is All You Need',
	publicationYear: 2017,
	authors: ['Vaswani', 'Shazeer'],
	citationCount: 100000,
	abstract: 'The dominant sequence transduction models…',
	sourceId: 'arxiv:1706.03762',
	references: [],
});

// ---- User Story 1: subscription shape ------------------------------------

check(
	'US1.1',
	'A subscription with a valid type/value/label/interval/last-checked/enabled is recognized as valid',
	() => {
		for (const t of ['keyword', 'author', 'arxivCategory']) {
			assert(isValidSubscription(validSub(t)), `type "${t}" should be accepted`);
		}
	},
);

check(
	'US1.2',
	'A check interval outside 6/12/24/48/72 is rejected and leaves the prior interval unchanged',
	() => {
		// assignCheckInterval keeps the prior value on a disallowed request…
		assert(assignCheckInterval(24, 10) === 24, 'disallowed 10 must leave prior 24 unchanged');
		assert(assignCheckInterval(24, 0) === 24, 'disallowed 0 must leave prior 24 unchanged');
		// …and accepts an allowed one.
		assert(assignCheckInterval(24, 48) === 48, 'allowed 48 must be accepted');
		// A record carrying a disallowed interval is itself invalid.
		assert(
			!isValidSubscription({ ...validSub('keyword'), checkIntervalHours: 10 as never }),
			'subscription with interval 10 must be invalid',
		);
	},
);

check('US1.3', 'A subscription missing a required attribute is identified as invalid', () => {
	const base = validSub('keyword');
	for (const key of ['type', 'value', 'label', 'checkIntervalHours', 'lastCheckedAt', 'enabled']) {
		const copy = { ...base } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidSubscription(copy), `missing "${key}" must be invalid`);
	}
	// A disallowed type is also rejected (Edge Case).
	assert(
		!isValidSubscription({ ...base, type: 'journal' as never }),
		'unknown subscription type must be invalid',
	);
});

// ---- User Story 2: paper shape + hold-back rule --------------------------

check('US2.1', 'A paper with all required attributes and a known year is recognized as valid', () => {
	assert(isValidPaper(validPaper()), 'a fully-populated paper must be valid');
});

check(
	'US2.2',
	'A paper with unknown publication year is held back (toPaper → undefined) until a year is known',
	() => {
		const candidate: PaperCandidate = {
			title: 'Preprint',
			publicationYear: undefined,
			authors: ['A'],
			citationCount: undefined,
			abstract: 'x',
			sourceId: 'arxiv:2301.00001',
			references: undefined,
		};
		assert(toPaper(candidate) === undefined, 'missing year must be held back (undefined)');
		const promoted = toPaper({ ...candidate, publicationYear: 2019 });
		assert(promoted !== undefined, 'once a year is known, promotion succeeds');
		assert(promoted!.publicationYear === 2019, 'promoted paper carries the known year');
		assert(isValidPaper(promoted!), 'promoted paper is a valid Paper');
	},
);

check('US2.3', 'A paper missing a required attribute is identified as invalid', () => {
	const base = validPaper();
	for (const key of ['title', 'publicationYear', 'authors', 'citationCount', 'abstract', 'sourceId', 'references']) {
		const copy = { ...base } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidPaper(copy), `missing "${key}" must be invalid`);
	}
	// An empty / non-numeric publication year is invalid (FR-009).
	assert(!isValidPaper({ ...base, publicationYear: undefined as never }), 'undefined year must be invalid');
});

// ---- User Story 3: settings shape + defaults ----------------------------

check(
	'US3.1',
	'Newly-loaded settings resolve to complete defaults (storage location, summarization, graph options)',
	() => {
		assert(
			typeof DEFAULT_PLUGIN_SETTINGS.storageLocation === 'string' &&
				DEFAULT_PLUGIN_SETTINGS.storageLocation.length > 0,
			'storageLocation default must be concrete and non-empty',
		);
		assert(
			typeof DEFAULT_PLUGIN_SETTINGS.summarizationEnabled === 'boolean',
			'summarizationEnabled default must be present',
		);
		assert(
			DEFAULT_PLUGIN_SETTINGS.graphDisplayOptions != null,
			'graphDisplayOptions default must be present',
		);
		assert(isValidPluginSettings(DEFAULT_PLUGIN_SETTINGS), 'the default settings must be valid');
	},
);

check('US3.2', 'Settings missing one of the three defined groups are identified as invalid', () => {
	for (const key of ['storageLocation', 'summarizationEnabled', 'graphDisplayOptions']) {
		const copy = { ...DEFAULT_PLUGIN_SETTINGS } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidPluginSettings(copy), `missing "${key}" must be invalid`);
	}
});

// ---- Success Criteria ----------------------------------------------------

skip(
	'SC-001',
	'Every later feature can define its data needs by referencing only this spec',
	'Process/documentation outcome — not verifiable by executing code.',
);

check('SC-002', '100% of subscriptions missing an attribute or using a bad interval are invalid', () => {
	const base = validSub('keyword');
	for (const key of ['type', 'value', 'label', 'checkIntervalHours', 'lastCheckedAt', 'enabled']) {
		const copy = { ...base } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidSubscription(copy), `missing "${key}" must be invalid`);
	}
	for (const bad of [5, 7, 13, 36, 96, 0, -6]) {
		assert(
			!isValidSubscription({ ...base, checkIntervalHours: bad as never }),
			`interval ${bad} must be invalid`,
		);
	}
});

check('SC-003', '100% of papers missing a year or any attribute are invalid', () => {
	const base = validPaper();
	for (const key of ['title', 'publicationYear', 'authors', 'citationCount', 'abstract', 'sourceId', 'references']) {
		const copy = { ...base } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidPaper(copy), `missing "${key}" must be invalid`);
	}
});

check('SC-004', '100% of newly loaded settings resolve to a complete default set', () => {
	assert(isValidPluginSettings(DEFAULT_PLUGIN_SETTINGS), 'defaults must validate');
	for (const key of ['storageLocation', 'summarizationEnabled', 'graphDisplayOptions']) {
		assert(key in DEFAULT_PLUGIN_SETTINGS, `default set must include "${key}"`);
	}
});

check(
	'SC-005',
	'Papers dedup by a provider-encoded sourceId; ids from different providers cannot collide',
	() => {
		assert(isPaperSourceId('arxiv:2301.12345'), 'valid arxiv id accepted');
		assert(isPaperSourceId('semanticScholar:649def34'), 'valid semanticScholar id accepted');
		assert(!isPaperSourceId('foo:1'), 'unknown provider rejected');
		assert(!isPaperSourceId('arxiv:'), 'empty local part rejected');
		assert(!isPaperSourceId('2301.12345'), 'id without a provider prefix rejected');
		assert(!isPaperSourceId(':x'), 'empty provider rejected');
		// Distinct providers cannot produce the same prefix, so two providers'
		// ids can never be equal — the dedup key is collision-free across providers.
		const arxivProvider = 'arxiv:1706.03762'.split(':')[0];
		const s2Provider = 'semanticScholar:1706.03762'.split(':')[0];
		assert(arxivProvider !== s2Provider, 'provider prefixes are distinct');
	},
);

// ---- Report --------------------------------------------------------------

for (const r of results) {
	if (r.status === 'PASS') {
		console.log(`[PASS] ${r.id} — ${r.desc}`);
	} else if (r.status === 'FAIL') {
		console.log(`[FAIL] ${r.id} — ${r.desc}: ${r.note}`);
	} else {
		console.log(`[SKIP] ${r.id} — ${r.desc} (${r.note})`);
	}
}

const passed = results.filter((r) => r.status === 'PASS').length;
const failed = results.filter((r) => r.status === 'FAIL').length;
const skipped = results.filter((r) => r.status === 'SKIP').length;

console.log(`\nSummary: ${passed} passed, ${failed} failed, ${skipped} skipped`);
process.exitCode = failed > 0 ? 1 : 0;
