// Generated by /spec-test for specs/001-core-data-models/spec.md
// Verifies the current src/models implementation against the spec's
// Acceptance Scenarios and Success Criteria. Run via esbuild + node
// (the repo's no-test-runner convention). Report-only.

import {
	isValidSubscription,
	assignCheckInterval,
	DEFAULT_CHECK_INTERVAL_HOURS,
	ALLOWED_CHECK_INTERVALS_HOURS,
} from '../../src/models/subscription';
import type { Subscription } from '../../src/models/subscription';
import { isValidPaper, toPaper, isPaperSourceId } from '../../src/models/paper';
import type { PaperCandidate, Paper } from '../../src/models/paper';
import { isValidPluginSettings, DEFAULT_PLUGIN_SETTINGS } from '../../src/models/settings';

type Status = 'PASS' | 'FAIL' | 'SKIP';
interface Result {
	id: string;
	desc: string;
	status: Status;
	note?: string;
}

const results: Result[] = [];

function check(id: string, desc: string, fn: () => void): void {
	try {
		fn();
		results.push({ id, desc, status: 'PASS' });
	} catch (e) {
		results.push({ id, desc, status: 'FAIL', note: (e as Error).message });
	}
}

function skip(id: string, desc: string, reason: string): void {
	results.push({ id, desc, status: 'SKIP', note: reason });
}

function assert(cond: boolean, msg: string): void {
	if (!cond) {
		throw new Error(msg);
	}
}

// ---- Fixtures -------------------------------------------------------------

const validSub = (type: string): Subscription => ({
	type: type as Subscription['type'],
	value: 'transformers',
	label: 'Transformers',
	checkIntervalHours: 24,
	lastCheckedAt: null,
	enabled: true,
});

const validPaper = (): Paper => ({
	title: 'Attention Is All You Need',
	publicationYear: 2017,
	authors: ['Vaswani', 'Shazeer'],
	citationCount: 100000,
	abstract: 'The dominant sequence transduction models…',
	sourceId: 'arxiv:1706.03762',
	references: ['arxiv:1409.0473'],
});

// The spec's real guarantee for the hold-back rule is that a paper never
// *becomes valid data* until it has a real year — via the two-step gate
// (toPaper then isValidPaper), not toPaper alone.
function becomesValidPaper(candidate: PaperCandidate): boolean {
	const p = toPaper(candidate);
	return p !== undefined && isValidPaper(p);
}

// ---- User Story 1: subscription shape ------------------------------------

check(
	'US1.1',
	'A subscription with a valid type/value/label/interval/last-checked/enabled is recognized as valid',
	() => {
		for (const t of ['keyword', 'author', 'arxivCategory']) {
			assert(isValidSubscription(validSub(t)), `type "${t}" should be accepted`);
		}
		// last-checked may be an actual timestamp, not only null (never-checked).
		assert(isValidSubscription({ ...validSub('keyword'), lastCheckedAt: 1_700_000_000_000 }), 'numeric lastCheckedAt accepted');
	},
);

check(
	'US1.2',
	'A check interval outside 6/12/24/48/72 is rejected and leaves the prior interval unchanged',
	() => {
		// Every allowed value is accepted…
		for (const ok of [6, 12, 24, 48, 72]) {
			assert(assignCheckInterval(24, ok) === ok, `allowed interval ${ok} must be accepted`);
		}
		// …and a disallowed request leaves the prior value untouched.
		for (const bad of [10, 0, -6, 36, 24.5]) {
			assert(assignCheckInterval(24, bad) === 24, `disallowed ${bad} must leave prior 24 unchanged`);
		}
		// A record carrying a disallowed interval is itself invalid.
		assert(!isValidSubscription({ ...validSub('keyword'), checkIntervalHours: 10 as never }), 'interval 10 must be invalid');
	},
);

check('US1.3', 'A subscription missing a required attribute is identified as invalid', () => {
	const base = validSub('keyword');
	// (a) missing (undefined) field.
	for (const key of ['type', 'value', 'label', 'checkIntervalHours', 'lastCheckedAt', 'enabled']) {
		const copy = { ...base } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidSubscription(copy), `missing "${key}" must be invalid`);
	}
	// (b) present-but-wrong-type field — proves it type-validates, not just presence-checks.
	assert(!isValidSubscription({ ...base, value: 123 as never }), 'numeric value must be invalid');
	assert(!isValidSubscription({ ...base, label: 456 as never }), 'numeric label must be invalid');
	assert(!isValidSubscription({ ...base, enabled: 'true' as never }), 'string enabled must be invalid');
	assert(!isValidSubscription({ ...base, lastCheckedAt: 'yesterday' as never }), 'string lastCheckedAt must be invalid');
	assert(!isValidSubscription({ ...base, checkIntervalHours: '24' as never }), 'string interval must be invalid');
	// (c) disallowed enum value (Edge Case).
	assert(!isValidSubscription({ ...base, type: 'journal' as never }), 'unknown subscription type must be invalid');
	assert(!isValidSubscription({ ...base, type: 42 as never }), 'non-string type must be invalid');
});

// ---- User Story 2: paper shape + hold-back rule --------------------------

check('US2.1', 'A paper with all required attributes and a known year is recognized as valid', () => {
	assert(isValidPaper(validPaper()), 'a fully-populated paper must be valid');
	assert(isValidPaper({ ...validPaper(), references: [] }), 'empty references is still valid');
});

check(
	'US2.2',
	'A paper with an unknown or empty publication year is held back until a real year is known',
	() => {
		const base: PaperCandidate = {
			title: 'Preprint',
			publicationYear: undefined,
			authors: ['A'],
			citationCount: undefined,
			abstract: 'x',
			sourceId: 'arxiv:2301.00001',
			references: undefined,
		};
		// Unknown year: the specific hold-back mechanism returns undefined.
		assert(toPaper(base) === undefined, 'undefined year must be held back (toPaper → undefined)');
		// Empty-but-not-undefined years (null, string) must also never become valid paper data.
		assert(!becomesValidPaper({ ...base, publicationYear: null as never }), 'null year must not become a valid paper');
		assert(!becomesValidPaper({ ...base, publicationYear: '2017' as never }), 'string year must not become a valid paper');
		assert(!becomesValidPaper({ ...base, publicationYear: NaN as never }), 'NaN year must not become a valid paper');
		assert(!becomesValidPaper({ ...base, publicationYear: Infinity as never }), 'Infinity year must not become a valid paper');
		// Once a real year is known, promotion succeeds and yields a valid Paper.
		const promoted = toPaper({ ...base, publicationYear: 2019 });
		assert(promoted !== undefined, 'a known year promotes');
		assert(promoted!.publicationYear === 2019, 'promoted paper carries the known year');
		assert(isValidPaper(promoted!), 'promoted paper is a valid Paper');
	},
);

check('US2.3', 'A paper missing or malformed in a required attribute is identified as invalid', () => {
	const base = validPaper();
	// (a) missing field.
	for (const key of ['title', 'publicationYear', 'authors', 'citationCount', 'abstract', 'sourceId', 'references']) {
		const copy = { ...base } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidPaper(copy), `missing "${key}" must be invalid`);
	}
	// (b) present-but-wrong-type.
	assert(!isValidPaper({ ...base, title: 123 as never }), 'numeric title invalid');
	assert(!isValidPaper({ ...base, citationCount: '100' as never }), 'string citationCount invalid');
	assert(!isValidPaper({ ...base, citationCount: NaN as never }), 'NaN citationCount invalid');
	assert(!isValidPaper({ ...base, citationCount: -3 as never }), 'negative citationCount invalid');
	assert(!isValidPaper({ ...base, publicationYear: '2017' as never }), 'string year invalid');
	assert(!isValidPaper({ ...base, publicationYear: NaN as never }), 'NaN year invalid');
	assert(!isValidPaper({ ...base, publicationYear: Infinity as never }), 'Infinity year invalid');
	// (c) collection fields with a bad element / non-array — exercises the .every() branches.
	assert(!isValidPaper({ ...base, authors: 'Vaswani' as never }), 'non-array authors invalid');
	assert(!isValidPaper({ ...base, authors: [1, 2] as never }), 'non-string author element invalid');
	assert(!isValidPaper({ ...base, references: 'arxiv:1' as never }), 'non-array references invalid');
	assert(!isValidPaper({ ...base, references: ['not-a-source-id'] as never }), 'malformed reference id invalid');
	assert(!isValidPaper({ ...base, references: ['arxiv:1409.0473', 999] as never }), 'non-string reference element invalid');
	// (d) source identifier with an unknown provider.
	assert(!isValidPaper({ ...base, sourceId: 'unknownProvider:1' as never }), 'unknown-provider sourceId invalid');
});

// ---- User Story 3: settings shape + defaults ----------------------------

check(
	'US3.1',
	'Newly-loaded settings resolve to complete defaults (storage location, summarization, graph options)',
	() => {
		assert(
			typeof DEFAULT_PLUGIN_SETTINGS.storageLocation === 'string' && DEFAULT_PLUGIN_SETTINGS.storageLocation.length > 0,
			'storageLocation default must be concrete and non-empty',
		);
		assert(typeof DEFAULT_PLUGIN_SETTINGS.summarizationEnabled === 'boolean', 'summarizationEnabled default must be present');
		assert(
			typeof DEFAULT_PLUGIN_SETTINGS.graphDisplayOptions?.layout === 'string' &&
				typeof DEFAULT_PLUGIN_SETTINGS.graphDisplayOptions?.colorScheme === 'string',
			'graphDisplayOptions default must have layout + colorScheme',
		);
		assert(isValidPluginSettings(DEFAULT_PLUGIN_SETTINGS), 'the default settings must be valid');
	},
);

check('US3.2', 'Settings missing or malformed in one of the three groups are identified as invalid', () => {
	// (a) missing group.
	for (const key of ['storageLocation', 'summarizationEnabled', 'graphDisplayOptions']) {
		const copy = { ...DEFAULT_PLUGIN_SETTINGS } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidPluginSettings(copy), `missing "${key}" must be invalid`);
	}
	// (b) empty / wrong-type values.
	assert(!isValidPluginSettings({ ...DEFAULT_PLUGIN_SETTINGS, storageLocation: '' }), 'empty storageLocation must be invalid (FR-011: concrete non-empty)');
	assert(!isValidPluginSettings({ ...DEFAULT_PLUGIN_SETTINGS, storageLocation: 123 as never }), 'numeric storageLocation invalid');
	assert(!isValidPluginSettings({ ...DEFAULT_PLUGIN_SETTINGS, summarizationEnabled: 'yes' as never }), 'string summarizationEnabled invalid');
	assert(!isValidPluginSettings({ ...DEFAULT_PLUGIN_SETTINGS, graphDisplayOptions: { layout: 'x' } as never }), 'graphDisplayOptions missing colorScheme invalid');
});

// ---- Success Criteria ----------------------------------------------------

skip(
	'SC-001',
	'Every later feature can define its data needs by referencing only this spec',
	'Process/documentation outcome — not verifiable by executing code.',
);

check('SC-002', '100% of subscriptions missing an attribute or using a bad interval are invalid', () => {
	const base = validSub('keyword');
	for (const key of ['type', 'value', 'label', 'checkIntervalHours', 'lastCheckedAt', 'enabled']) {
		const copy = { ...base } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidSubscription(copy), `missing "${key}" must be invalid`);
	}
	for (const bad of [5, 7, 13, 36, 96, 0, -6, 24.5]) {
		assert(!isValidSubscription({ ...base, checkIntervalHours: bad as never }), `interval ${bad} must be invalid`);
	}
});

check('SC-003', '100% of papers missing a year or any attribute are invalid', () => {
	const base = validPaper();
	for (const key of ['title', 'publicationYear', 'authors', 'citationCount', 'abstract', 'sourceId', 'references']) {
		const copy = { ...base } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidPaper(copy), `missing "${key}" must be invalid`);
	}
});

check('SC-004', '100% of newly loaded settings resolve to a complete, valid default set', () => {
	assert(isValidPluginSettings(DEFAULT_PLUGIN_SETTINGS), 'defaults must validate');
	// Each of the three groups is individually load-bearing: dropping any one invalidates the set.
	for (const key of ['storageLocation', 'summarizationEnabled', 'graphDisplayOptions']) {
		const copy = { ...DEFAULT_PLUGIN_SETTINGS } as Record<string, unknown>;
		delete copy[key];
		assert(!isValidPluginSettings(copy), `default set must genuinely require "${key}"`);
	}
});

check('SC-005', 'A paper source identifier is provider-encoded and collision-free across providers', () => {
	assert(isPaperSourceId('arxiv:2301.12345'), 'valid arxiv id accepted');
	assert(isPaperSourceId('semanticScholar:649def34'), 'valid semanticScholar id accepted');
	assert(!isPaperSourceId('foo:1'), 'unknown provider rejected');
	assert(!isPaperSourceId('arxiv:'), 'empty local part rejected');
	assert(!isPaperSourceId('2301.12345'), 'id without a provider prefix rejected');
	assert(!isPaperSourceId(':x'), 'empty provider rejected');
	// Distinct providers cannot share a prefix, so ids across providers can never be equal.
	const arxivProvider = 'arxiv:1706.03762'.split(':')[0];
	const s2Provider = 'semanticScholar:1706.03762'.split(':')[0];
	assert(arxivProvider !== s2Provider, 'provider prefixes are distinct');
});

skip(
	'SC-005-dedup',
	'Actual deduplication of papers by source identifier',
	'001 only guarantees the id is collision-free; performing deduplication is owned by collection (002), so the dedup mechanism is not verifiable at the data-model layer.',
);

// ---- Edge Cases ----------------------------------------------------------

check('EC-1', 'A paper with no known year is held back, not discarded — and can be reconsidered once a year is known', () => {
	const candidate: PaperCandidate = {
		title: 'Preprint',
		publicationYear: undefined,
		authors: ['A'],
		citationCount: undefined,
		abstract: 'x',
		sourceId: 'arxiv:2401.00001',
		references: undefined,
	};
	assert(toPaper(candidate) === undefined, 'no-year paper is held back');
	// "Not discarded": the candidate is unchanged and can be promoted later.
	assert(candidate.publicationYear === undefined, 'the candidate is not mutated by a failed promotion');
	assert(becomesValidPaper({ ...candidate, publicationYear: 2022 }), 'the same candidate promotes once a year is known');
});

check('EC-2', 'An out-of-range interval is rejected and the subscription keeps its previous valid interval', () => {
	assert(assignCheckInterval(6, 999) === 6, 'keeps prior 6');
	assert(assignCheckInterval(72, 13) === 72, 'keeps prior 72');
	assert(assignCheckInterval(12, 24) === 24, 'a valid change is still applied');
});

check('EC-3', 'A subscription type outside keyword/author/arXiv category is rejected', () => {
	assert(!isValidSubscription({ ...validSub('keyword'), type: 'conference' as never }), 'unknown type rejected');
	assert(!isValidSubscription({ ...validSub('keyword'), type: '' as never }), 'empty type rejected');
});

check('EC-4', 'A subscription created without an explicit interval receives the default (24h, an allowed value)', () => {
	assert(DEFAULT_CHECK_INTERVAL_HOURS === 24, 'default interval is 24h (spec Assumption)');
	assert((ALLOWED_CHECK_INTERVALS_HOURS as readonly number[]).includes(DEFAULT_CHECK_INTERVAL_HOURS), 'the default is itself an allowed interval');
});

skip(
	'EC-4-apply',
	'Actually applying the default interval when a subscription is created without one',
	'001 exports the default constant; applying it during subscription creation is owned by collection/UI (002/008).',
);

check('EC-5', 'On first run (nothing saved), the full set of default settings is available and valid', () => {
	assert(isValidPluginSettings(DEFAULT_PLUGIN_SETTINGS), 'defaults are a complete, valid set');
	for (const key of ['storageLocation', 'summarizationEnabled', 'graphDisplayOptions']) {
		assert(key in DEFAULT_PLUGIN_SETTINGS, `default set includes "${key}"`);
	}
});

// ---- Report --------------------------------------------------------------

for (const r of results) {
	if (r.status === 'PASS') {
		console.log(`[PASS] ${r.id} — ${r.desc}`);
	} else if (r.status === 'FAIL') {
		console.log(`[FAIL] ${r.id} — ${r.desc}: ${r.note}`);
	} else {
		console.log(`[SKIP] ${r.id} — ${r.desc} (${r.note})`);
	}
}

const passed = results.filter((r) => r.status === 'PASS').length;
const failed = results.filter((r) => r.status === 'FAIL').length;
const skipped = results.filter((r) => r.status === 'SKIP').length;

console.log(`\nSummary: ${passed} passed, ${failed} failed, ${skipped} skipped`);
process.exitCode = failed > 0 ? 1 : 0;
