// Generated by /specs-chain-test for the chain:
//   001-core-data-models → 002-subscription-paper-collection →
//   003-paper-note-persistence → 005-manual-paper-refresh
//
// Verifies how these specs INTEGRATE (seams + whole-system flow), not each in isolation.
// Runs against the real src/ exports via esbuild + node with 'obsidian' aliased to a
// programmable requestUrl shim + a DOMParser polyfill, so the 002 enrichment leg and the
// 005 refresh leg run their real client/parser code with deterministic inputs and zero
// live network calls. Report-only (does not modify src/).

import type { EntrySpec } from './_obsidian-shim';

// --- polyfills (used at call time) ---------------------------------------------------
function makeEntryElement(spec: EntrySpec): unknown {
	const node = (t?: string) => (t === undefined ? [] : [{ textContent: t }]);
	const authorNodes = (spec.authors ?? []).map((name) => ({
		getElementsByTagName: (t: string) => (t === 'name' ? [{ textContent: name }] : []),
	}));
	const map: Record<string, unknown[]> = {
		id: node(spec.id), title: node(spec.title), summary: node(spec.summary),
		published: node(spec.published), author: authorNodes,
	};
	return { getElementsByTagName: (t: string) => map[t] ?? [] };
}
class FakeDOMParser {
	parseFromString(text: string): unknown {
		const data = JSON.parse(text) as { entries: EntrySpec[] };
		const entries = data.entries.map(makeEntryElement);
		return { getElementsByTagName: (t: string) => (t === 'entry' ? entries : []) };
	}
}
/* eslint-disable @typescript-eslint/no-explicit-any */
(globalThis as any).window = globalThis;
(globalThis as any).DOMParser = FakeDOMParser;
/* eslint-enable @typescript-eslint/no-explicit-any */

// 001 — core data models
import type { Paper, PaperCandidate, PaperSourceId } from '../../src/models/paper';
import { isValidPaper, toPaper } from '../../src/models/paper';
// 002 — collection (promotion, embedding, S2 parse, real pipeline)
import { promote } from '../../src/collection/promotion';
import { computeBaselineEmbedding, BASELINE_EMBEDDING_MODEL } from '../../src/collection/embedding';
import { parseSemanticScholarPaper, toPaperSourceId } from '../../src/collection/semanticScholarParser';
import { runCollectionPass } from '../../src/collection/pipeline';
import type { PipelineHooks, SummaryResult } from '../../src/collection/types';
// 003 — persistence
import { PaperStore } from '../../src/persistence/store';
import { InMemoryFileStore } from '../../src/persistence/filestore';
import { parseNote } from '../../src/persistence/note';
// 005 — refresh
import { createConcurrencyGuard } from '../../src/refresh/concurrencyGuard';
import { refreshOne } from '../../src/refresh/refreshOne';

type Status = 'PASS' | 'FAIL' | 'SKIP';
interface Result { id: string; desc: string; status: Status; note?: string }
const results: Result[] = [];
function report(r: Result): void {
	results.push(r);
	if (r.status === 'PASS') console.log(`[PASS] ${r.id} — ${r.desc}`);
	else if (r.status === 'FAIL') console.log(`[FAIL] ${r.id} — ${r.desc}: ${r.note}`);
	else console.log(`[SKIP] ${r.id} — ${r.desc} (${r.note})`);
}
async function check(id: string, desc: string, fn: () => void | Promise<void>): Promise<void> {
	try { await fn(); report({ id, desc, status: 'PASS' }); }
	catch (e) { report({ id, desc, status: 'FAIL', note: (e as Error).message }); }
}
function skip(id: string, desc: string, reason: string): void { report({ id, desc, status: 'SKIP', note: reason }); }
function assert(cond: boolean, msg: string): void { if (!cond) throw new Error(msg); }
function eqArr(a: readonly number[] | null, b: readonly number[] | null): boolean {
	if (a === null || b === null) return a === b;
	return a.length === b.length && a.every((v, i) => v === b[i]);
}

interface Api {
	arxiv: Map<string, EntrySpec | 'notfound' | 'throw'>;
	s2: Map<string, { citationCount: number; references?: unknown[] } | '404' | 'null'>;
	counts: { arxiv: number; s2single: number; s2batch: number };
}
function resetApi(): Api {
	const a: Api = { arxiv: new Map(), s2: new Map(), counts: { arxiv: 0, s2single: 0, s2batch: 0 } };
	(globalThis as unknown as { __api: Api }).__api = a;
	return a;
}
const YEAR = new Date().getFullYear();
const SID = 'arxiv:2301.77777' as PaperSourceId;
function baseOf(sid: PaperSourceId): string { return sid.slice(sid.indexOf(':') + 1); }

// A raw arXiv-style candidate (001 shape) as 002's discovery would yield: no citation data
// (undefined), no embedding yet (undefined).
function candidate(over: Partial<PaperCandidate> = {}): PaperCandidate {
	return {
		title: 'Head Title', publicationYear: YEAR, authors: ['Ada'], citationCount: undefined,
		abstract: 'Head Abstract', sourceId: SID, references: undefined,
		embedding: undefined, embeddingModel: undefined, embeddingSource: undefined, ...over,
	};
}
function newStore(): { store: PaperStore; fs: InMemoryFileStore } {
	const fs = new InMemoryFileStore();
	return { store: new PaperStore(fs), fs };
}
function arxivEntry(id: string, over: Partial<EntrySpec> = {}): EntrySpec {
	return { id: `http://arxiv.org/abs/${id}v1`, title: 'Head Title', summary: 'Head Abstract', published: `${YEAR}-01-01`, authors: ['Ada'], ...over };
}
async function findMd(fs: InMemoryFileStore, sid: string): Promise<string> {
	for (const f of await fs.list()) if (f.endsWith('.md')) { const t = await fs.read(f); if (t?.includes(sid)) return f; }
	throw new Error(`no .md for ${sid}`);
}

async function main(): Promise<void> {
	// ============ Seam 001 → 002 ============
	await check('C1', '[001→002] promote() lifts a candidate to a 001-valid Paper; citationsKnown mirrors enrichment', () => {
		const enriched = promote(candidate({ citationCount: 7, references: ['arxiv:1900.00001' as PaperSourceId] }));
		assert(enriched !== undefined && isValidPaper(enriched), 'enriched candidate promotes to a valid Paper');
		assert(enriched!.citationCount === 7 && enriched!.citationsKnown === true, 'known citations carried, citationsKnown true');
		const bare = promote(candidate({ citationCount: undefined }));
		assert(bare !== undefined && isValidPaper(bare), 'un-enriched candidate still promotes');
		assert(bare!.citationCount === 0 && bare!.citationsKnown === false, 'un-enriched → count 0, citationsKnown false (001/002 FR-018)');
	});

	await check('C2', '[001→002 negative] a candidate 001 rejects (missing/NaN year) never promotes — nothing can flow downstream', () => {
		assert(promote(candidate({ publicationYear: undefined })) === undefined, 'undefined year held back');
		assert(promote(candidate({ publicationYear: Number.NaN })) === undefined, 'NaN year held back');
		// The 001 gate itself agrees (producer side).
		assert(toPaper(candidate({ publicationYear: undefined })) === undefined, '001 toPaper rejects missing year');
	});

	await check('C3', "[002→001 embedding] 002's baseline embedding produces a 001-valid embedded Paper", () => {
		const p = promote(candidate())!;
		const emb = computeBaselineEmbedding(p.title, p.abstract);
		p.embedding = emb.embedding; p.embeddingModel = emb.embeddingModel; p.embeddingSource = emb.embeddingSource;
		assert(isValidPaper(p), '002-embedded Paper satisfies 001 isValidPaper');
		assert(Array.isArray(p.embedding) && p.embedding!.length === 2048, 'embedding is a 2048-dim numeric vector');
		assert(p.embeddingModel === BASELINE_EMBEDDING_MODEL && p.embeddingSource === 'local', 'model/source set per 002 FR-044');
		// A pending (null) embedding is ALSO a valid 001 Paper — never a hold-back (001 FR-021).
		const pending = promote(candidate())!;
		assert(isValidPaper(pending) && pending.embedding === null, 'pending (null) embedding is still 001-valid');
	});

	// ============ Seam 002/001 → 003 ============
	await check('C4', '[002/001→003] a promoted+embedded Paper round-trips through 003 store; note frontmatter mirrors the shared subset', async () => {
		resetApi(); const { store, fs } = newStore();
		const p = promote(candidate({ citationCount: 4, references: ['arxiv:1800.00002' as PaperSourceId] }))!;
		const emb = computeBaselineEmbedding(p.title, p.abstract);
		p.embedding = emb.embedding; p.embeddingModel = emb.embeddingModel; p.embeddingSource = emb.embeddingSource;
		await store.upsert({ paper: p });
		const round = (await store.get(SID))!;
		assert(JSON.stringify(round) === JSON.stringify(p), '003 get() round-trips the exact 001 Paper');
		const fm = parseNote(await fs.read(await findMd(fs, SID)) as string).frontmatter;
		assert(fm['title'] === p.title, 'frontmatter title mirrors Paper');
		assert(JSON.stringify(fm['authors']) === JSON.stringify(p.authors), 'frontmatter authors mirror Paper');
		assert(fm['publicationYear'] === p.publicationYear, 'frontmatter publicationYear mirrors Paper');
		assert(fm['citationCount'] === p.citationCount, 'frontmatter citationCount mirrors Paper');
		assert(fm['pg3d_sourceId'] === p.sourceId, 'frontmatter pg3d_sourceId mirrors Paper');
	});

	await check('C5', '[001/002→003 negative] fields OUTSIDE the shared subset do not leak into the note frontmatter (003 FR-002)', async () => {
		resetApi(); const { store, fs } = newStore();
		const p = promote(candidate({ citationCount: 4, references: ['arxiv:1800.00002' as PaperSourceId] }))!;
		const emb = computeBaselineEmbedding(p.title, p.abstract);
		p.embedding = emb.embedding; p.embeddingModel = emb.embeddingModel; p.embeddingSource = emb.embeddingSource;
		await store.upsert({ paper: p });
		const fm = parseNote(await fs.read(await findMd(fs, SID)) as string).frontmatter;
		for (const leaked of ['references', 'schemaVersion', 'createdAt', 'updatedAt', 'embedding', 'embeddingModel', 'embeddingSource', 'abstract']) {
			assert(!(leaked in fm), `frontmatter must not carry '${leaked}'`);
		}
	});

	// ============ Seam 002 → 005 ============
	await check('C6', "[002→005] a content-changing refresh recomputes the embedding via 002's computeBaselineEmbedding", async () => {
		const a = resetApi(); const { store } = newStore();
		const p = promote(candidate())!;
		const emb0 = computeBaselineEmbedding(p.title, p.abstract);
		p.embedding = emb0.embedding; p.embeddingModel = emb0.embeddingModel; p.embeddingSource = emb0.embeddingSource;
		await store.upsert({ paper: p });
		a.arxiv.set(baseOf(SID), arxivEntry(baseOf(SID), { summary: 'Revised Abstract' }));
		a.s2.set(baseOf(SID), { citationCount: 2, references: [] });
		await refreshOne(store, SID, createConcurrencyGuard(), {}, () => false, () => undefined, () => ({ provider: 'bundled' }));
		const after = (await store.get(SID))!;
		assert(eqArr(after.embedding, computeBaselineEmbedding('Head Title', 'Revised Abstract').embedding), "005's recomputed embedding == 002's baseline of the new content");
		assert(after.embeddingModel === BASELINE_EMBEDDING_MODEL, 'embedding model still 002 baseline');
	});

	await check('C7', "[002→005] a single refresh applies citations parsed by 002's parseSemanticScholarPaper/toPaperSourceId", async () => {
		const a = resetApi(); const { store } = newStore();
		await store.upsert({ paper: promote(candidate())! });
		const s2body = { citationCount: 33, references: [{ paperId: 'x', externalIds: { ArXiv: '1700.00003v2' } }] };
		a.arxiv.set(baseOf(SID), arxivEntry(baseOf(SID)));
		a.s2.set(baseOf(SID), s2body);
		await refreshOne(store, SID, createConcurrencyGuard(), {}, () => false, () => undefined, () => ({ provider: 'bundled' }));
		const after = (await store.get(SID))!;
		// Cross-check against 002's own parser applied to the same body.
		const parsed = parseSemanticScholarPaper(s2body);
		assert(after.citationCount === parsed.citationCount && after.citationCount === 33, 'citation count applied via 002 parser');
		assert(after.references.length === 1 && after.references[0] === toPaperSourceId(parsed.references[0]!), 'reference sourceId built via 002 toPaperSourceId (version-stripped)');
		assert(after.references[0] === 'arxiv:1700.00003', 'arXiv version suffix stripped across the seam');
	});

	// ============ Seam 003 → 005 ============
	await check('C8', '[003→005] refresh reads via 003 get() and writes via 003 upsert(); the user-owned note body is preserved', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		await store.upsert({ paper: promote(candidate())! });
		const md = await findMd(fs, SID);
		await fs.write(md, (await fs.read(md))! + 'MY OWN NOTES\n');
		a.arxiv.set(baseOf(SID), arxivEntry(baseOf(SID), { summary: 'Newer Abstract' }));
		a.s2.set(baseOf(SID), { citationCount: 1, references: [] });
		const out = await refreshOne(store, SID, createConcurrencyGuard(), {}, () => false, () => undefined, () => ({ provider: 'bundled' }));
		assert(out.status === 'updated', 'refresh completes through the 003 store');
		assert((await store.get(SID))!.abstract === 'Newer Abstract', 'updated Paper read back through 003 get()');
		assert((await fs.read(md))!.includes('MY OWN NOTES'), 'user body preserved across the 003↔005 seam');
	});

	await check('C9', '[003→005 negative] refresh of a sourceId absent from the 003 store makes no provider call and writes nothing', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		const before = (await fs.list()).length;
		const out = await refreshOne(store, 'arxiv:0000.00000' as PaperSourceId, createConcurrencyGuard(), {}, () => false, () => undefined, () => ({ provider: 'bundled' }));
		assert(out.status === 'notFound', 'absent sourceId → notFound');
		assert(a.counts.arxiv === 0 && a.counts.s2single === 0, 'no provider call crossed the seam');
		assert((await fs.list()).length === before, 'store untouched');
	});

	// ============ Whole-system end-to-end ============
	await check('E1', '[system] candidate → REAL 002 pipeline → 003 store → 005 refresh → 003 read-back stays 001-valid throughout', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		// Head: enrichment (through 002's real batch client + the shim) returns citations.
		a.s2.set(baseOf(SID), { citationCount: 9, references: [{ paperId: 'r', externalIds: { ArXiv: '1600.00004' } }] });
		const hooks: PipelineHooks = {
			persist: async (paper: Paper, summary?: SummaryResult) =>
				store.upsert({ paper, summary: summary?.summary, futureDirections: summary?.futureDirections }),
			alreadyPersisted: async (sid: PaperSourceId) => store.has(sid),
		};
		async function* candidates(): AsyncIterable<PaperCandidate> { yield candidate(); }
		// Drive the REAL 002 pipeline: dedup → batched enrich (shim) → promote (001) →
		// attach baseline embedding (002 FR-044) → persist hook (003). Summarization off.
		await runCollectionPass(candidates(), hooks, () => false, () => undefined, undefined, () => ({ provider: 'bundled' }));

		// After the 001→002→003 head: the paper exists, is 001-valid, enriched, embedded.
		const collected = await store.get(SID);
		assert(collected !== undefined && isValidPaper(collected), 'collected Paper is present and 001-valid');
		assert(collected!.citationCount === 9 && collected!.citationsKnown === true, 'enrichment threaded through promotion');
		assert(collected!.references.length === 1 && collected!.references[0] === 'arxiv:1600.00004', 'reference sourceId threaded (version-stripped)');
		assert(eqArr(collected!.embedding, computeBaselineEmbedding('Head Title', 'Head Abstract').embedding), 'baseline embedding attached at collection');
		const mdPath = await findMd(fs, SID);
		await fs.write(mdPath, (await fs.read(mdPath))! + 'USER TAIL\n'); // user writes in the note

		// Tail: 005 refresh with a newer arXiv revision (changed abstract) + higher citations.
		a.arxiv.set(baseOf(SID), arxivEntry(baseOf(SID), { title: 'Head Title', summary: 'End-to-end Revised Abstract' }));
		a.s2.set(baseOf(SID), { citationCount: 21, references: [] });
		const out = await refreshOne(store, SID, createConcurrencyGuard(), {}, () => false, () => undefined, () => ({ provider: 'bundled' }));
		assert(out.status === 'updated', 'refresh completes end-to-end');

		// Emergent, whole-chain invariants that no single seam/spec test alone would catch:
		const final = (await store.get(SID))!;
		assert(isValidPaper(final), 'the artifact remains 001-valid after threading 001→002→003→005→003');
		assert(final.abstract === 'End-to-end Revised Abstract', 'newer revision content applied at the tail');
		assert(final.citationCount === 21, 'refreshed citation count read back through 003');
		assert(final.publicationYear === YEAR, 'publicationYear (the 002/005 window key) stayed stable across the whole chain');
		assert(eqArr(final.embedding, computeBaselineEmbedding('Head Title', 'End-to-end Revised Abstract').embedding), 'embedding stayed consistent with 002 computation after content change');
		assert((await fs.read(mdPath))!.includes('USER TAIL'), 'user-owned note region untouched across the entire pipeline');
	});

	skip('E2', '[system] LLM-canonical embedding threaded through collection + refresh', 'the 004-owned LLM embedding provider is a stub in 002 (upgradeEmbedding returns undefined for llm); the whole chain is exercised on the bundled canonical provider by E1');

	const p = results.filter((r) => r.status === 'PASS').length;
	const f = results.filter((r) => r.status === 'FAIL').length;
	const s = results.filter((r) => r.status === 'SKIP').length;
	console.log(`\nSummary: ${p} passed, ${f} failed, ${s} skipped`);
	process.exitCode = f > 0 ? 1 : 0;
}
main().catch((e) => { console.error('HARNESS ERROR', e); process.exitCode = 1; });
