// Generated by /spec-test for specs/005-manual-paper-refresh/spec.md
// Verifies the CURRENT src/refresh + touched src/collection implementation against the
// spec's Acceptance Scenarios, Success Criteria, and concrete-outcome Edge Cases.
// Report-only (does not modify src/). Run via esbuild + node (the repo's no-test-runner
// convention) with 'obsidian' aliased to _obsidian-shim.ts and a DOMParser polyfill, so
// the real fetchArxivEntryById/parseArxivEntry/fetchSemanticScholar{Paper,Batch}/refresh
// code runs end-to-end against crafted, deterministic responses — no live network call.

import type { EntrySpec } from './_obsidian-shim';

// --- polyfills (used only at call time, inside main()) -------------------------------
// Fake <entry> Element supporting exactly what parseArxivEntry reads.
function makeEntryElement(spec: EntrySpec): unknown {
	const node = (t?: string) => (t === undefined ? [] : [{ textContent: t }]);
	const authorNodes = (spec.authors ?? []).map((name) => ({
		getElementsByTagName: (t: string) => (t === 'name' ? [{ textContent: name }] : []),
	}));
	const map: Record<string, unknown[]> = {
		id: node(spec.id),
		title: node(spec.title),
		summary: node(spec.summary),
		published: node(spec.published),
		author: authorNodes,
	};
	return { getElementsByTagName: (t: string) => map[t] ?? [] };
}
class FakeDOMParser {
	parseFromString(text: string): unknown {
		const data = JSON.parse(text) as { entries: EntrySpec[] };
		const entries = data.entries.map(makeEntryElement);
		return { getElementsByTagName: (t: string) => (t === 'entry' ? entries : []) };
	}
}
/* eslint-disable @typescript-eslint/no-explicit-any */
(globalThis as any).window = globalThis;
(globalThis as any).DOMParser = FakeDOMParser;
/* eslint-enable @typescript-eslint/no-explicit-any */

import type { Paper, PaperSourceId } from '../../src/models/paper';
import { PaperStore } from '../../src/persistence/store';
import { InMemoryFileStore } from '../../src/persistence/filestore';
import { computeBaselineEmbedding, BASELINE_EMBEDDING_MODEL } from '../../src/collection/embedding';
import { createConcurrencyGuard } from '../../src/refresh/concurrencyGuard';
import { refreshOne } from '../../src/refresh/refreshOne';
import { runBulkRefresh } from '../../src/refresh/bulkRefresh';

type Status = 'PASS' | 'FAIL' | 'SKIP';
interface Result { id: string; desc: string; status: Status; note?: string }
const results: Result[] = [];
function report(r: Result): void {
	results.push(r);
	if (r.status === 'PASS') console.log(`[PASS] ${r.id} — ${r.desc}`);
	else if (r.status === 'FAIL') console.log(`[FAIL] ${r.id} — ${r.desc}: ${r.note}`);
	else console.log(`[SKIP] ${r.id} — ${r.desc} (${r.note})`);
}
async function check(id: string, desc: string, fn: () => void | Promise<void>): Promise<void> {
	try { await fn(); report({ id, desc, status: 'PASS' }); }
	catch (e) { report({ id, desc, status: 'FAIL', note: (e as Error).message }); }
}
function skip(id: string, desc: string, reason: string): void { report({ id, desc, status: 'SKIP', note: reason }); }
function assert(cond: boolean, msg: string): void { if (!cond) throw new Error(msg); }
function eqArr(a: readonly number[] | null, b: readonly number[] | null): boolean {
	if (a === null || b === null) return a === b;
	return a.length === b.length && a.every((v, i) => v === b[i]);
}

// --- programmable provider state -----------------------------------------------------
interface Api {
	arxiv: Map<string, EntrySpec | 'notfound' | 'throw'>;
	s2: Map<string, { citationCount: number; references?: unknown[] } | '404' | 'null'>;
	counts: { arxiv: number; s2single: number; s2batch: number };
}
function resetApi(): Api {
	const a: Api = { arxiv: new Map(), s2: new Map(), counts: { arxiv: 0, s2single: 0, s2batch: 0 } };
	(globalThis as unknown as { __api: Api }).__api = a;
	return a;
}
const YEAR = new Date().getFullYear();

// --- fixtures ------------------------------------------------------------------------
const hooksResult = { summary: 'GEN SUMMARY', futureDirections: 'GEN FUTURE' };
let summarizeCalls = 0;
const hooks = { summarize: async () => { summarizeCalls += 1; return hooksResult; } };
const enabled = () => true;
const disabled = () => false;
const noKey = () => undefined;
const bundled = () => ({ provider: 'bundled' as const });

function paper(over: Partial<Paper> & { sourceId: PaperSourceId }): Paper {
	return {
		title: 'OLD TITLE', publicationYear: YEAR, authors: ['Alice'], citationCount: 0,
		citationsKnown: true, abstract: 'OLD ABSTRACT', sourceId: over.sourceId, references: [],
		embedding: null, embeddingModel: null, embeddingSource: null, ...over,
	};
}
function newStore(): { store: PaperStore; fs: InMemoryFileStore } {
	const fs = new InMemoryFileStore();
	return { store: new PaperStore(fs), fs };
}
async function seed(store: PaperStore, p: Paper): Promise<void> { await store.upsert({ paper: p }); }
function entry(id: string, over: Partial<EntrySpec> = {}): EntrySpec {
	return { id: `http://arxiv.org/abs/${id}v1`, title: 'OLD TITLE', summary: 'OLD ABSTRACT', published: `${YEAR}-01-01`, authors: ['Alice'], ...over };
}
async function snapshot(fs: InMemoryFileStore): Promise<Map<string, string>> {
	const m = new Map<string, string>();
	for (const f of await fs.list()) m.set(f, (await fs.read(f))!);
	return m;
}
async function findMd(fs: InMemoryFileStore, sourceId: string): Promise<string> {
	for (const f of await fs.list()) if (f.endsWith('.md')) { const t = await fs.read(f); if (t?.includes(sourceId)) return f; }
	throw new Error(`no .md for ${sourceId}`);
}
const A = 'arxiv:2301.00001' as PaperSourceId;
const B = 'arxiv:2020.00002' as PaperSourceId;
const C = 'arxiv:2301.00003' as PaperSourceId;
function baseOf(sid: PaperSourceId): string { return sid.slice(sid.indexOf(':') + 1); }

async function main(): Promise<void> {
	// ================= User Story 1 =================
	await check('US1.1', 'Refresh re-checks citation count, references, title/abstract/authors; publicationYear unchanged', async () => {
		const a = resetApi(); const { store } = newStore();
		await seed(store, paper({ sourceId: A, publicationYear: YEAR, title: 'OLD TITLE', abstract: 'OLD ABSTRACT', authors: ['Alice'] }));
		a.arxiv.set(baseOf(A), entry(baseOf(A), { title: 'NEW TITLE', summary: 'NEW ABSTRACT', authors: ['Bob', 'Carol'] }));
		a.s2.set(baseOf(A), { citationCount: 12, references: [{ paperId: 'p9', externalIds: { ArXiv: '2101.11111' } }] });
		const out = await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(out.status === 'updated', `status updated (got ${out.status})`);
		const p = (await store.get(A))!;
		assert(p.title === 'NEW TITLE' && p.abstract === 'NEW ABSTRACT', 'title/abstract updated');
		assert(JSON.stringify(p.authors) === JSON.stringify(['Bob', 'Carol']), 'authors updated');
		assert(p.citationCount === 12 && p.citationsKnown === true, 'citation count + known updated');
		assert(p.references.length === 1 && p.references[0] === 'arxiv:2101.11111', 'references updated');
		assert(p.publicationYear === YEAR, 'publicationYear carried through unchanged');
	});

	await check('US1.2', 'Refresh updates the existing record + note managed region (not a new note); user body preserved', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		await seed(store, paper({ sourceId: A }));
		const md = await findMd(fs, A);
		await fs.write(md, (await fs.read(md))! + 'USER_WROTE_THIS\n');
		const filesBefore = (await fs.list()).filter((f) => f.endsWith('.md')).length;
		a.arxiv.set(baseOf(A), entry(baseOf(A), { summary: 'NEW ABSTRACT' }));
		a.s2.set(baseOf(A), { citationCount: 3 });
		await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert((await fs.list()).filter((f) => f.endsWith('.md')).length === filesBefore, 'no new note created (same note updated)');
		assert((await store.get(A))!.abstract === 'NEW ABSTRACT', 'JSON record reflects new abstract');
		assert((await fs.read(md))!.includes('USER_WROTE_THIS'), 'user body preserved');
		// Summarization is enabled and the abstract changed, so 003 renders the regenerated
		// summary (not the raw abstract) into the managed region — proving it was rebuilt.
		assert((await fs.read(md))!.includes('GEN SUMMARY'), 'note managed region rebuilt from the refresh');
	});

	await check('US1.3', 'Abstract change (summarization enabled) regenerates summary exactly once; disabled does not, but fields still update', async () => {
		const a = resetApi(); const { store } = newStore();
		await seed(store, paper({ sourceId: A }));
		a.arxiv.set(baseOf(A), entry(baseOf(A), { summary: 'NEW ABSTRACT' }));
		a.s2.set(baseOf(A), { citationCount: 4 });
		summarizeCalls = 0;
		await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(summarizeCalls === 1, `enabled: regenerated once (got ${summarizeCalls})`);
		// disabled
		const a2 = resetApi(); const { store: s2 } = newStore();
		await seed(s2, paper({ sourceId: A }));
		a2.arxiv.set(baseOf(A), entry(baseOf(A), { summary: 'ANOTHER NEW ABSTRACT' }));
		a2.s2.set(baseOf(A), { citationCount: 6 });
		summarizeCalls = 0;
		await refreshOne(s2, A, createConcurrencyGuard(), hooks, disabled, noKey, bundled);
		assert(summarizeCalls === 0, 'disabled: 004 not invoked');
		const p = (await s2.get(A))!;
		assert(p.abstract === 'ANOTHER NEW ABSTRACT' && p.citationCount === 6, 'disabled: citation/content still updated');
	});

	await check('US1.4', 'Embedding recomputed when abstract changes; left unchanged when content identical', async () => {
		const a = resetApi(); const { store } = newStore();
		const seedEmb = computeBaselineEmbedding('OLD TITLE', 'OLD ABSTRACT');
		await seed(store, paper({ sourceId: A, embedding: seedEmb.embedding, embeddingModel: seedEmb.embeddingModel, embeddingSource: 'local' }));
		a.arxiv.set(baseOf(A), entry(baseOf(A), { summary: 'NEW ABSTRACT' }));
		a.s2.set(baseOf(A), { citationCount: 1 });
		await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		let p = (await store.get(A))!;
		assert(eqArr(p.embedding, computeBaselineEmbedding('OLD TITLE', 'NEW ABSTRACT').embedding), 'embedding recomputed to new content');
		assert(p.embeddingModel === BASELINE_EMBEDDING_MODEL && p.embeddingSource === 'local', 'embedding model/source set');
		// unchanged content
		const a2 = resetApi(); const { store: s2 } = newStore();
		await seed(s2, paper({ sourceId: A, embedding: seedEmb.embedding, embeddingModel: seedEmb.embeddingModel, embeddingSource: 'local' }));
		a2.arxiv.set(baseOf(A), entry(baseOf(A))); // identical title/abstract
		a2.s2.set(baseOf(A), { citationCount: 9 });
		await refreshOne(s2, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		p = (await s2.get(A))!;
		assert(eqArr(p.embedding, seedEmb.embedding) && p.embeddingModel === seedEmb.embeddingModel, 'embedding unchanged when content identical');
	});

	await check('US1.5', 'Refreshing one paper leaves other papers unaffected', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		await seed(store, paper({ sourceId: A }));
		await seed(store, paper({ sourceId: B, publicationYear: YEAR - 5, citationCount: 3 }));
		const before = new Map<string, string>();
		for (const [f, c] of await snapshot(fs)) if (c.includes(B)) before.set(f, c);
		a.arxiv.set(baseOf(A), entry(baseOf(A), { summary: 'NEW ABSTRACT' }));
		a.s2.set(baseOf(A), { citationCount: 7 });
		await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		for (const [f, c] of before) assert((await fs.read(f)) === c, `Paper B file unchanged: ${f}`);
	});

	// ================= User Story 2 =================
	await check('US2.1', 'Bulk refresh re-checks only papers within the last year', async () => {
		const a = resetApi(); const { store } = newStore();
		await seed(store, paper({ sourceId: A, publicationYear: YEAR }));
		await seed(store, paper({ sourceId: B, publicationYear: YEAR - 5 }));
		await seed(store, paper({ sourceId: C, publicationYear: YEAR - 1 }));
		for (const sid of [A, C]) a.arxiv.set(baseOf(sid), entry(baseOf(sid)));
		a.s2.set(baseOf(A), { citationCount: 1 }); a.s2.set(baseOf(C), { citationCount: 1 });
		const res = await runBulkRefresh(store, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(!('status' in res), 'bulk returned a result');
		if (!('status' in res)) assert(res.matchedCount === 2, `matched exactly A and C (got ${res.matchedCount})`);
		assert(a.counts.arxiv === 2, `only 2 arXiv lookups, B skipped (got ${a.counts.arxiv})`);
	});

	await check('US2.2', 'Bulk reports progress (papers processed vs total) as it proceeds', async () => {
		const a = resetApi(); const { store } = newStore();
		await seed(store, paper({ sourceId: A })); await seed(store, paper({ sourceId: C }));
		for (const sid of [A, C]) { a.arxiv.set(baseOf(sid), entry(baseOf(sid))); a.s2.set(baseOf(sid), { citationCount: 2 }); }
		const seen: Array<[number, number]> = [];
		await runBulkRefresh(store, createConcurrencyGuard(), hooks, enabled, noKey, bundled, (d, t) => seen.push([d, t]));
		assert(seen.length === 2 && seen[0]![0] === 1 && seen[1]![0] === 2, 'progress increments 1..2');
		assert(seen.every(([, t]) => t === 2), 'total reported as matched count');
	});

	await check('US2.3', 'One paper failing does not stop the rest; failures are collected as one summary', async () => {
		const a = resetApi(); const { store } = newStore();
		await seed(store, paper({ sourceId: A })); await seed(store, paper({ sourceId: C }));
		a.arxiv.set(baseOf(A), entry(baseOf(A), { summary: 'NEW ABSTRACT' })); a.arxiv.set(baseOf(C), 'notfound');
		a.s2.set(baseOf(A), { citationCount: 5 }); a.s2.set(baseOf(C), { citationCount: 5 });
		const res = await runBulkRefresh(store, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(!('status' in res), 'result returned');
		if (!('status' in res)) {
			assert(res.failures.length === 1 && res.failures[0]!.sourceId === C, 'one failure for C');
			assert(res.matchedCount === 2, 'both papers attempted');
		}
		assert((await store.get(A))!.abstract === 'NEW ABSTRACT', 'A still refreshed despite C failing');
	});

	await check('US2.4', 'Bulk does not process a paper a single refresh is already handling (no double-refresh)', async () => {
		const a = resetApi(); const { store } = newStore();
		await seed(store, paper({ sourceId: A })); await seed(store, paper({ sourceId: C }));
		for (const sid of [A, C]) { a.arxiv.set(baseOf(sid), entry(baseOf(sid))); a.s2.set(baseOf(sid), { citationCount: 2 }); }
		const guard = createConcurrencyGuard();
		guard.claimSingle(A); // a single refresh holds A
		const res = await runBulkRefresh(store, guard, hooks, enabled, noKey, bundled);
		assert(!('status' in res), 'result returned');
		// A is skipped (held by single) and not counted as a failure; C is processed.
		if (!('status' in res)) assert(res.failures.length === 0, 'skipped paper is not a failure');
		assert(a.arxiv.get(baseOf(A)) !== undefined && a.counts.arxiv === 1, 'only C fetched from arXiv; A never double-processed');
	});

	skip('US2.5', 'Rate-limit partway through bulk paces subsequent requests more conservatively without aborting', 'the adaptive backoff delay is internal to bulkRefresh with no externally observable signal at this layer; the non-abort half is covered by US2.3/SC-008');

	await check('US2.6', 'Cancelling a bulk stops before the next paper; processed keep updates, unreached untouched, restart immediate', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		const ids = ['arxiv:2301.10001', 'arxiv:2301.10002', 'arxiv:2301.10003', 'arxiv:2301.10004'] as PaperSourceId[];
		for (const sid of ids) { await seed(store, paper({ sourceId: sid, citationCount: 0 })); a.arxiv.set(baseOf(sid), entry(baseOf(sid))); a.s2.set(baseOf(sid), { citationCount: 7 }); }
		const before = await snapshot(fs);
		const guard = createConcurrencyGuard();
		const res = await runBulkRefresh(store, guard, hooks, enabled, noKey, bundled, (done) => { if (done === 1) guard.requestBulkCancel(); });
		assert(!('status' in res), 'result returned');
		if (!('status' in res)) assert(res.matchedCount >= 1 && res.matchedCount < 4, `stopped early (got ${res.matchedCount})`);
		let updated = 0;
		for (const sid of ids) if ((await store.get(sid))!.citationCount === 7) updated += 1;
		assert(updated === 1, `exactly one processed before cancel (got ${updated})`);
		// unreached papers byte-identical
		for (const sid of ids) {
			if ((await store.get(sid))!.citationCount === 0) {
				for (const [f, c] of before) if (c.includes(sid)) assert((await fs.read(f)) === c, `unreached ${sid} byte-identical (${f})`);
			}
		}
		assert(guard.isBulkCancelRequested() === false, 'cancel flag cleared after run');
		const res2 = await runBulkRefresh(store, guard, hooks, enabled, noKey, bundled);
		assert(!('status' in res2), 'a new run starts immediately (not alreadyRunning)');
	});

	// ================= Success Criteria =================
	await check('SC-001', "After refresh, citation count reflects the latest provider value", async () => {
		const a = resetApi(); const { store } = newStore();
		await seed(store, paper({ sourceId: A, citationCount: 2 }));
		a.arxiv.set(baseOf(A), entry(baseOf(A))); a.s2.set(baseOf(A), { citationCount: 42 });
		await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert((await store.get(A))!.citationCount === 42, 'latest citation count applied');
	});

	await check('SC-002', 'User-written note body is unchanged after a refresh', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		await seed(store, paper({ sourceId: A }));
		const md = await findMd(fs, A);
		await fs.write(md, (await fs.read(md))! + 'HANDWRITTEN NOTES — keep me\n');
		a.arxiv.set(baseOf(A), entry(baseOf(A), { title: 'NEW TITLE', summary: 'NEW ABSTRACT' })); a.s2.set(baseOf(A), { citationCount: 5 });
		await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert((await fs.read(md))!.includes('HANDWRITTEN NOTES — keep me'), 'handwritten body intact');
	});

	await check('SC-003', 'Papers not requested for refresh have zero changes', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		await seed(store, paper({ sourceId: A })); await seed(store, paper({ sourceId: B, publicationYear: YEAR - 3 }));
		const before = new Map<string, string>();
		for (const [f, c] of await snapshot(fs)) if (c.includes(B)) before.set(f, c);
		a.arxiv.set(baseOf(A), entry(baseOf(A), { summary: 'NEW ABSTRACT' })); a.s2.set(baseOf(A), { citationCount: 8 });
		await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		for (const [f, c] of before) assert((await fs.read(f)) === c, `B unchanged: ${f}`);
	});

	await check('SC-004', 'arXiv-fail / not-found / store-absent leaves pairing intact; a Semantic Scholar-only failure does not', async () => {
		// arXiv not found -> notFound, data intact
		let a = resetApi(); let { store } = newStore();
		await seed(store, paper({ sourceId: A, abstract: 'KEEP' }));
		a.arxiv.set(baseOf(A), 'notfound');
		let out = await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(out.status === 'notFound' && (await store.get(A))!.abstract === 'KEEP', 'arXiv not-found kept data');
		// arXiv throw -> error, data intact
		a = resetApi(); ({ store } = newStore());
		await seed(store, paper({ sourceId: A, abstract: 'KEEP2' }));
		a.arxiv.set(baseOf(A), 'throw');
		out = await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(out.status === 'error' && (await store.get(A))!.abstract === 'KEEP2', 'arXiv failure kept data');
		// S2-only failure -> still updated
		a = resetApi(); ({ store } = newStore());
		await seed(store, paper({ sourceId: A, citationCount: 11, citationsKnown: true }));
		a.arxiv.set(baseOf(A), entry(baseOf(A), { summary: 'NEW ABSTRACT' })); a.s2.set(baseOf(A), '404');
		out = await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(out.status === 'updated', 'S2-only failure is not a refresh failure');
		const p = (await store.get(A))!;
		assert(p.abstract === 'NEW ABSTRACT' && p.citationCount === 11, 'content applied, prior citations preserved');
	});
	skip('SC-004-notify', 'User is informed of the failure', 'the on-screen notice is rendered by 008; refresh only returns the outcome status (spec Assumptions)');

	await check('SC-005', 'A paper already being refreshed is never processed twice concurrently', async () => {
		const { store } = newStore(); resetApi();
		await seed(store, paper({ sourceId: A }));
		const guard = createConcurrencyGuard(); guard.claimSingle(A);
		const out = await refreshOne(store, A, guard, hooks, enabled, noKey, bundled);
		assert(out.status === 'alreadyInFlight', `alreadyInFlight (got ${out.status})`);
	});

	await check('SC-006', 'Bulk touches exactly the last-year set; zero papers outside the window modified', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		await seed(store, paper({ sourceId: A, publicationYear: YEAR }));
		await seed(store, paper({ sourceId: B, publicationYear: YEAR - 2 }));
		await seed(store, paper({ sourceId: C, publicationYear: YEAR - 1 }));
		const bBefore = new Map<string, string>();
		for (const [f, c] of await snapshot(fs)) if (c.includes(B)) bBefore.set(f, c);
		for (const sid of [A, C]) { a.arxiv.set(baseOf(sid), entry(baseOf(sid), { summary: 'NEW ABSTRACT' })); a.s2.set(baseOf(sid), { citationCount: 3 }); }
		const res = await runBulkRefresh(store, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		if (!('status' in res)) assert(res.matchedCount === 2, 'exactly A and C matched');
		for (const [f, c] of bBefore) assert((await fs.read(f)) === c, `out-of-window B unchanged: ${f}`);
	});

	await check('SC-007', 'Bulk completes without blocking and well under a 3s-per-paper pace (small-N proxy for 100+)', async () => {
		const a = resetApi(); const { store } = newStore();
		const ids = ['arxiv:2301.20001', 'arxiv:2301.20002', 'arxiv:2301.20003'] as PaperSourceId[];
		for (const sid of ids) { await seed(store, paper({ sourceId: sid })); a.arxiv.set(baseOf(sid), entry(baseOf(sid))); a.s2.set(baseOf(sid), { citationCount: 1 }); }
		const t0 = Date.now();
		const res = await runBulkRefresh(store, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		const elapsed = Date.now() - t0;
		if (!('status' in res)) assert(res.matchedCount === 3, 'all processed');
		assert(elapsed < 3 * 3000, `elapsed ${elapsed}ms << 3s/paper (${3 * 3000}ms)`);
		assert(a.counts.s2batch === 1, 'citation lookups issued as one batch (not per-paper)');
	});
	skip('SC-007-scale', 'A 100+ paper bulk stays responsive under real timing', 'literal 100+ scale/UI-responsiveness is a manual/8-owned observation; asserted here structurally with a 3-paper proxy');

	await check('SC-008', 'Individual failures never abort the run; every matched paper attempted; failures surfaced as one summary', async () => {
		const a = resetApi(); const { store } = newStore();
		const ids = ['arxiv:2301.30001', 'arxiv:2301.30002', 'arxiv:2301.30003'] as PaperSourceId[];
		await seed(store, paper({ sourceId: ids[0]! })); a.arxiv.set(baseOf(ids[0]!), entry(baseOf(ids[0]!)));
		await seed(store, paper({ sourceId: ids[1]! })); a.arxiv.set(baseOf(ids[1]!), 'notfound');
		await seed(store, paper({ sourceId: ids[2]! })); a.arxiv.set(baseOf(ids[2]!), 'throw');
		for (const sid of ids) a.s2.set(baseOf(sid), { citationCount: 1 });
		const res = await runBulkRefresh(store, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		if (!('status' in res)) {
			assert(res.matchedCount === 3, 'all three attempted');
			assert(res.failures.length === 2, 'both failures collected into one summary');
		}
	});

	await check('SC-009', "Title/abstract/authors match provider's current values (newer revision), no version bookkeeping", async () => {
		const a = resetApi(); const { store } = newStore();
		await seed(store, paper({ sourceId: A, title: 'v1 title', abstract: 'v1 abstract', authors: ['Solo'] }));
		a.arxiv.set(baseOf(A), entry(baseOf(A), { title: 'v2 title', summary: 'v2 abstract', authors: ['Solo', 'NewCoauthor'] }));
		a.s2.set(baseOf(A), { citationCount: 0 });
		await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		const p = (await store.get(A))!;
		assert(p.title === 'v2 title' && p.abstract === 'v2 abstract', 'newer revision content applied');
		assert(JSON.stringify(p.authors) === JSON.stringify(['Solo', 'NewCoauthor']), 'authors reflect current revision');
	});

	await check('SC-010', 'Regenerate iff (abstract changed OR uncited-status changed) AND enabled; both → exactly one; neither/disabled → zero', async () => {
		const run = async (seedOver: Partial<Paper>, arxivOver: Partial<EntrySpec>, s2count: number, isEnabled: () => boolean): Promise<number> => {
			const a = resetApi(); const { store } = newStore();
			await seed(store, paper({ sourceId: A, ...seedOver }));
			a.arxiv.set(baseOf(A), entry(baseOf(A), arxivOver)); a.s2.set(baseOf(A), { citationCount: s2count });
			summarizeCalls = 0;
			await refreshOne(store, A, createConcurrencyGuard(), hooks, isEnabled, noKey, bundled);
			return summarizeCalls;
		};
		assert((await run({ abstract: 'OLD ABSTRACT', citationCount: 3, citationsKnown: true }, { summary: 'NEW' }, 3, enabled)) === 1, 'abstract-only change → 1');
		assert((await run({ abstract: 'OLD ABSTRACT', citationCount: 0, citationsKnown: true }, {}, 5, enabled)) === 1, 'status-only flip → 1');
		assert((await run({ abstract: 'OLD ABSTRACT', citationCount: 0, citationsKnown: true }, { summary: 'NEW' }, 5, enabled)) === 1, 'both true → exactly 1');
		assert((await run({ abstract: 'OLD ABSTRACT', citationCount: 3, citationsKnown: true }, {}, 9, enabled)) === 0, 'neither → 0');
		assert((await run({ abstract: 'OLD ABSTRACT', citationCount: 0, citationsKnown: true }, { summary: 'NEW' }, 5, disabled)) === 0, 'disabled → 0');
	});

	await check('SC-011', 'Bulk over N papers issues ceil(N/500) citation requests (typically 1), never N individual lookups', async () => {
		const a = resetApi(); const { store } = newStore();
		const ids = Array.from({ length: 6 }, (_, i) => `arxiv:2301.4000${i}` as PaperSourceId);
		for (const sid of ids) { await seed(store, paper({ sourceId: sid })); a.arxiv.set(baseOf(sid), entry(baseOf(sid))); a.s2.set(baseOf(sid), { citationCount: 1 }); }
		await runBulkRefresh(store, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(a.counts.s2batch === 1, `one batch request for 6 papers (got ${a.counts.s2batch})`);
		assert(a.counts.s2single === 0, 'zero per-paper citation lookups in bulk');
	});

	await check('SC-012', 'Embedding recomputed iff title or abstract changed', async () => {
		// title-only change triggers recompute
		let a = resetApi(); let { store } = newStore();
		const seedEmb = computeBaselineEmbedding('OLD TITLE', 'OLD ABSTRACT');
		await seed(store, paper({ sourceId: A, embedding: seedEmb.embedding, embeddingModel: seedEmb.embeddingModel, embeddingSource: 'local' }));
		a.arxiv.set(baseOf(A), entry(baseOf(A), { title: 'DIFFERENT TITLE' })); a.s2.set(baseOf(A), { citationCount: 1 });
		await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(eqArr((await store.get(A))!.embedding, computeBaselineEmbedding('DIFFERENT TITLE', 'OLD ABSTRACT').embedding), 'title change recomputes embedding');
		// citation-only change leaves embedding
		a = resetApi(); ({ store } = newStore());
		await seed(store, paper({ sourceId: A, embedding: seedEmb.embedding, embeddingModel: seedEmb.embeddingModel, embeddingSource: 'local' }));
		a.arxiv.set(baseOf(A), entry(baseOf(A))); a.s2.set(baseOf(A), { citationCount: 99 });
		await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		const p = (await store.get(A))!;
		assert(eqArr(p.embedding, seedEmb.embedding) && p.embeddingModel === seedEmb.embeddingModel && p.embeddingSource === 'local', 'citation-only change leaves embedding + model + source');
	});

	await check('SC-013', 'Cancelled bulk: zero partial, processed reflect full refresh, unreached byte-identical, immediate restart', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		const ids = ['arxiv:2301.50001', 'arxiv:2301.50002', 'arxiv:2301.50003', 'arxiv:2301.50004'] as PaperSourceId[];
		for (const sid of ids) { await seed(store, paper({ sourceId: sid, citationCount: 0 })); a.arxiv.set(baseOf(sid), entry(baseOf(sid), { summary: 'NEW ABSTRACT' })); a.s2.set(baseOf(sid), { citationCount: 5 }); }
		const before = await snapshot(fs);
		const guard = createConcurrencyGuard();
		const res = await runBulkRefresh(store, guard, hooks, enabled, noKey, bundled, (done) => { if (done === 1) guard.requestBulkCancel(); });
		let processed = 0, untouched = 0;
		for (const sid of ids) {
			const p = (await store.get(sid))!;
			if (p.abstract === 'NEW ABSTRACT' && p.citationCount === 5) processed += 1;
			else {
				untouched += 1;
				for (const [f, c] of before) if (c.includes(sid)) assert((await fs.read(f)) === c, `unreached ${sid} byte-identical`);
			}
		}
		assert(processed >= 1 && untouched >= 1 && processed + untouched === 4, `partial split (processed ${processed}, untouched ${untouched})`);
		if (!('status' in res)) assert(res.matchedCount === processed, 'matchedCount equals fully-processed count (no partial state)');
		const res2 = await runBulkRefresh(store, guard, hooks, enabled, noKey, bundled);
		assert(!('status' in res2), 'restart is immediate');
	});

	// ================= Edge Cases (distinct from the above) =================
	await check('EC-store-absent', 'Refresh of a sourceId absent from the store fails before any provider call', async () => {
		const a = resetApi(); const { store } = newStore();
		const out = await refreshOne(store, 'arxiv:9999.99999' as PaperSourceId, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(out.status === 'notFound', `notFound (got ${out.status})`);
		assert(a.counts.arxiv === 0 && a.counts.s2single === 0, 'no provider call made');
	});

	await check('EC-bulk-already-running', 'A second bulk trigger while one is running is rejected, not run concurrently', async () => {
		const a = resetApi(); const { store } = newStore();
		await seed(store, paper({ sourceId: A }));
		a.arxiv.set(baseOf(A), entry(baseOf(A))); a.s2.set(baseOf(A), { citationCount: 1 });
		const guard = createConcurrencyGuard();
		const p1 = runBulkRefresh(store, guard, hooks, enabled, noKey, bundled);
		const p2 = await runBulkRefresh(store, guard, hooks, enabled, noKey, bundled);
		assert('status' in p2 && p2.status === 'alreadyRunning', 'second bulk rejected');
		await p1;
	});

	await check('EC-abstract-unchanged', 'Unchanged content refreshes normally with no 004 call (common case)', async () => {
		const a = resetApi(); const { store } = newStore();
		await seed(store, paper({ sourceId: A, citationCount: 4, citationsKnown: true }));
		a.arxiv.set(baseOf(A), entry(baseOf(A))); a.s2.set(baseOf(A), { citationCount: 4 });
		summarizeCalls = 0;
		const out = await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(out.status === 'updated' && summarizeCalls === 0, 'completes with no regeneration');
	});

	await check('EC-summarization-off-midflight', 'Summarization toggled off mid-flight discards the stale generated result', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		await seed(store, paper({ sourceId: A }));
		a.arxiv.set(baseOf(A), entry(baseOf(A), { summary: 'NEW ABSTRACT' })); a.s2.set(baseOf(A), { citationCount: 2 });
		let live = true;
		const isEnabled = () => live;
		// The hook fires (proving the trigger condition held), but flips the live setting
		// off before it resolves — refreshOne must re-read and discard the result.
		const togglingHooks = { summarize: async () => { live = false; return hooksResult; } };
		const out = await refreshOne(store, A, createConcurrencyGuard(), togglingHooks, isEnabled, noKey, bundled);
		assert(out.status === 'updated', 'refresh still completes');
		const md = await fs.read(await findMd(fs, A));
		assert(md !== null && md.includes('NEW ABSTRACT'), 'content still applied');
		assert(md !== null && !md.includes('GEN SUMMARY') && !md.includes('GEN FUTURE'), 'stale generated summary discarded (abstract shown, not the summary)');
	});

	await check('EC-citation-status-matrix', 'Citation-driven regeneration fires only on a confirmed uncited-status flip', async () => {
		const run = async (seedOver: Partial<Paper>, s2count: number): Promise<number> => {
			const a = resetApi(); const { store } = newStore();
			await seed(store, paper({ sourceId: A, ...seedOver }));
			a.arxiv.set(baseOf(A), entry(baseOf(A))); a.s2.set(baseOf(A), { citationCount: s2count });
			summarizeCalls = 0;
			await refreshOne(store, A, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
			return summarizeCalls;
		};
		assert((await run({ citationCount: 0, citationsKnown: true }, 3)) === 1, 'uncited→cited regenerates');
		assert((await run({ citationCount: 5, citationsKnown: true }, 0)) === 1, 'cited→uncited regenerates');
		assert((await run({ citationCount: 0, citationsKnown: false }, 0)) === 1, 'un-enriched→confirmed-uncited regenerates');
		assert((await run({ citationCount: 0, citationsKnown: false }, 4)) === 0, 'un-enriched→cited does not');
		assert((await run({ citationCount: 5, citationsKnown: true }, 9)) === 0, 'cited count change (same status) does not');
	});

	await check('EC-bulk-batches-citations-arxiv-individual', 'Bulk batches citation lookups but fetches arXiv content per paper', async () => {
		const a = resetApi(); const { store } = newStore();
		const ids = ['arxiv:2301.60001', 'arxiv:2301.60002', 'arxiv:2301.60003'] as PaperSourceId[];
		for (const sid of ids) { await seed(store, paper({ sourceId: sid })); a.arxiv.set(baseOf(sid), entry(baseOf(sid))); a.s2.set(baseOf(sid), { citationCount: 1 }); }
		await runBulkRefresh(store, createConcurrencyGuard(), hooks, enabled, noKey, bundled);
		assert(a.counts.s2batch === 1 && a.counts.s2single === 0, 'citations via one batch call');
		assert(a.counts.arxiv === 3, 'arXiv content fetched individually per paper');
	});

	// ================= summary =================
	const p = results.filter((r) => r.status === 'PASS').length;
	const f = results.filter((r) => r.status === 'FAIL').length;
	const s = results.filter((r) => r.status === 'SKIP').length;
	console.log(`\nSummary: ${p} passed, ${f} failed, ${s} skipped`);
	process.exitCode = f > 0 ? 1 : 0;
}

main().catch((e) => { console.error('HARNESS ERROR', e); process.exitCode = 1; });
