// Generated by /specs-chain-test for the chain:
//   002-subscription-paper-collection -> 003-paper-note-persistence
//
// Verifies how 002 (collection) and 003 (persistence) integrate, from both angles the
// command requires: per-seam connection points (C<k>) and the whole-system pipeline
// threaded end-to-end (E<k>). Uses the REAL exported code on both sides of every seam —
// 002's promote()/PipelineHooks and 003's PaperStore/wrap/renderNote — never a re-derived
// copy. Report-only; run via esbuild + node (the repo's no-test-runner convention).
//
// THE SEAM. 002 turns a provider response into an 001 PaperCandidate, then promote()s it
// to a Paper. 003 consumes a Paper: PaperStore.upsert() wraps it into a record + note, and
// PaperStore.has()/get() read it back. Crucially, 002 does not import 003 — it declares the
// hand-off as PipelineHooks { persist, alreadyPersisted } (types.ts) so it can be built
// before 003 exists. The integration question this suite answers is therefore: does 003's
// PaperStore actually satisfy that injected contract, and do a promoted Paper's fields
// survive the record/note round trip with the exact subset 003 FR-002 mandates?

import { promote } from '../../src/collection/promotion';
import type { PipelineHooks } from '../../src/collection/types';
import {
	toPaper,
	isValidPaper,
	type Paper,
	type PaperCandidate,
} from '../../src/models/paper';
import { PaperStore } from '../../src/persistence/store';
import { InMemoryFileStore } from '../../src/persistence/filestore';
import { parseNote } from '../../src/persistence/note';

type Status = 'PASS' | 'FAIL' | 'SKIP';
interface Result {
	id: string;
	desc: string;
	status: Status;
	error?: string;
	reason?: string;
}
const results: Result[] = [];

function check(id: string, desc: string, fn: () => void | Promise<void>): Promise<void> {
	return Promise.resolve()
		.then(fn)
		.then(
			() => {
				results.push({ id, desc, status: 'PASS' });
			},
			(err: unknown) => {
				results.push({ id, desc, status: 'FAIL', error: err instanceof Error ? err.message : String(err) });
			},
		);
}
function skip(id: string, desc: string, reason: string): void {
	results.push({ id, desc, status: 'SKIP', reason });
}

function assert(cond: unknown, message: string): asserts cond {
	if (!cond) throw new Error(message);
}
// Order-independent structural equality, so a field-reorder never masquerades as a diff.
function stable(value: unknown): string {
	return JSON.stringify(value, (_k, v) => {
		if (v && typeof v === 'object' && !Array.isArray(v)) {
			return Object.fromEntries(Object.entries(v as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)));
		}
		return v;
	});
}

// A candidate shaped exactly as 002's parsers/enrichment hand to promote(): an
// enriched arXiv paper (citationCount known, a baseline local embedding present).
function enrichedCandidate(overrides: Partial<PaperCandidate> = {}): PaperCandidate {
	return {
		title: 'Attention Is All You Need',
		publicationYear: 2017,
		authors: ['Ashish Vaswani', 'Noam Shazeer'],
		citationCount: 42,
		abstract: 'We propose the Transformer, a model architecture eschewing recurrence.',
		sourceId: 'arxiv:1706.03762',
		references: ['arxiv:1409.0473'],
		embedding: [0.6, 0.8],
		embeddingModel: 'local-minilm',
		embeddingSource: 'local',
		...overrides,
	};
}

async function firstMd(fs: InMemoryFileStore): Promise<string> {
	const files = await fs.list();
	const md = files.find((f) => f.endsWith('.md'));
	assert(md, 'expected a .md note to have been written');
	const text = await fs.read(md);
	assert(text !== null, 'expected the .md note to be readable');
	return text;
}

async function main(): Promise<void> {
	// ---- Per-seam scenarios (2a) ---------------------------------------------

	// C1 [002->003] a promoted Paper is accepted by 003's persist path and its every
	// field survives the record round trip byte-for-byte.
	await check('C1', '[002->003 persist] promoted Paper round-trips through PaperStore unchanged', async () => {
		const paper = promote(enrichedCandidate());
		assert(paper, 'promote() should return a Paper for a candidate with a real year');
		const store = new PaperStore(new InMemoryFileStore());
		await store.upsert({ paper });
		const got = await store.get(paper.sourceId);
		assert(got, 'get() should return the persisted paper');
		assert(stable(got) === stable(paper), `round-tripped paper differs:\n  in : ${stable(paper)}\n  out: ${stable(got)}`);
	});

	// C2 [002->003] THE mesh: 003's PaperStore structurally satisfies 002's injected
	// PipelineHooks contract, and driving 002's hooks actually persists via 003. That this
	// object type-checks is itself the cross-spec proof the two signatures agree.
	await check('C2', '[002->003 hooks] PaperStore satisfies 002 PipelineHooks.persist/alreadyPersisted', async () => {
		const store = new PaperStore(new InMemoryFileStore());
		const hooks: PipelineHooks = {
			persist: (paper, summary) =>
				store.upsert({ paper, summary: summary?.summary, futureDirections: summary?.futureDirections }),
			alreadyPersisted: async (sourceId) => store.has(sourceId),
		};
		const paper = promote(enrichedCandidate());
		assert(paper, 'promote() should return a Paper');
		assert((await hooks.alreadyPersisted(paper.sourceId)) === false, 'should not be persisted before the pipeline runs');
		await hooks.persist(paper);
		assert((await hooks.alreadyPersisted(paper.sourceId)) === true, 'should be persisted after hooks.persist');
	});

	// C3 [002->003 note] the FR-002 mirrored subset in the note frontmatter equals the
	// promoted Paper's own fields (title/authors/publicationYear/citationCount/sourceId).
	await check('C3', '[002->003 note] note frontmatter mirrors the promoted Paper subset', async () => {
		const paper = promote(enrichedCandidate());
		assert(paper, 'promote() should return a Paper');
		const fs = new InMemoryFileStore();
		await new PaperStore(fs).upsert({ paper });
		const fm = parseNote(await firstMd(fs)).frontmatter;
		assert(fm['title'] === paper.title, 'title mismatch');
		assert(stable(fm['authors']) === stable(paper.authors), 'authors mismatch');
		assert(fm['publicationYear'] === paper.publicationYear, 'publicationYear mismatch');
		assert(fm['citationCount'] === paper.citationCount, 'citationCount mismatch');
		assert(fm['pg3d_sourceId'] === paper.sourceId, 'sourceId mismatch');
		assert(fm['readState'] === 'unread', 'default readState should be unread');
	});

	// C4 [002->003 note] subset boundary: fields OUTSIDE the mirrored subset
	// (embedding / schemaVersion / abstract / timestamps) must NOT leak into frontmatter,
	// while the mirrored subset (references three-state, collectedVia) DOES appear
	// (003 FR-002; references amended into the subset 2026-07-11). A single-spec test
	// cannot catch this cross-seam leak.
	await check('C4', '[002->003 note] non-subset fields do not leak; references + collectedVia are mirrored', async () => {
		const paper = promote(enrichedCandidate());
		assert(paper, 'promote() should return a Paper');
		const fs = new InMemoryFileStore();
		await new PaperStore(fs).upsert({ paper });
		const fm = parseNote(await firstMd(fs)).frontmatter;
		for (const leaked of ['embedding', 'embeddingModel', 'embeddingSource', 'schemaVersion', 'abstract', 'createdAt', 'updatedAt']) {
			assert(!(leaked in fm), `frontmatter must not carry '${leaked}', but it did: ${stable(fm)}`);
		}
		// Mirrored subset present (references three-state + collectedVia).
		assert(stable(fm.references) === stable(['arxiv:1409.0473']), `references (confirmed) not mirrored: ${stable(fm)}`);
		assert('collectedVia' in fm, `collectedVia not mirrored: ${stable(fm)}`);
	});

	// C5 [002->003] negative: a candidate 001/002 HOLDS BACK (missing year) never yields a
	// valid downstream artifact. promote() returns undefined, so nothing can be persisted,
	// and the would-be shape is not a valid Paper.
	await check('C5', '[002->003] a held-back (missing-year) candidate can never become a valid persisted record', async () => {
		const held = promote(enrichedCandidate({ publicationYear: undefined }));
		assert(held === undefined, 'promote() must hold back a candidate with no year');
		const nanYear = promote(enrichedCandidate({ publicationYear: Number.NaN }));
		assert(nanYear === undefined, 'promote() must hold back a candidate with a NaN year');
		// And the raw candidate shape is not a valid Paper, so no downstream record is valid.
		assert(isValidPaper(enrichedCandidate({ publicationYear: undefined })) === false, 'a yearless candidate must not validate as a Paper');
	});

	// C6 [002->003 dedup] the has()-by-sourceId that 002 uses for its alreadyPersisted
	// dedup flips false -> true exactly across the persist seam.
	await check('C6', '[002->003 dedup] PaperStore.has(sourceId) is false pre-persist, true post-persist', async () => {
		const paper = promote(enrichedCandidate());
		assert(paper, 'promote() should return a Paper');
		const store = new PaperStore(new InMemoryFileStore());
		assert(store.has(paper.sourceId) === false, 'has() should be false before upsert');
		await store.upsert({ paper });
		assert(store.has(paper.sourceId) === true, 'has() should be true after upsert');
	});

	// C7 [002->003] emergent: the unknown-vs-zero citation distinction 002 encodes in
	// citationsKnown survives persistence. An arXiv-only candidate (citationCount unknown)
	// persists as citationCount 0 WITH citationsKnown=false, and reads back unchanged — so
	// downstream (004/007) can still tell un-enriched from confirmed-zero after a save.
	await check('C7', '[002->003] citationsKnown (unknown-vs-zero) distinction survives the persist round trip', async () => {
		const arxivOnly = promote(enrichedCandidate({ citationCount: undefined, references: undefined }));
		assert(arxivOnly, 'promote() should return a Paper for an arXiv-only candidate');
		assert(arxivOnly.citationCount === 0 && arxivOnly.citationsKnown === false, 'arXiv-only promotion should be citationCount 0 / citationsKnown false');
		const store = new PaperStore(new InMemoryFileStore());
		await store.upsert({ paper: arxivOnly });
		const got = await store.get(arxivOnly.sourceId);
		assert(got, 'get() should return the persisted paper');
		assert(got.citationCount === 0 && got.citationsKnown === false, `distinction lost across persistence: ${stable(got)}`);
	});

	// ---- Whole-system end-to-end scenarios (2b) ------------------------------

	// E1 [system] the full pipeline threaded through EVERY implemented seam in chain order:
	// PaperCandidate --(002 promote)--> Paper --(003 upsert)--> record+note --(003 get)-->
	// Paper. Asserts the emergent round-trip fidelity of the whole chain, including the
	// embedding VECTOR (which lives only in the .json, never the note) surviving intact.
	await check('E1', '[system] candidate -> promote(002) -> upsert(003) -> get(003) preserves the whole Paper incl. embedding', async () => {
		const candidate = enrichedCandidate();
		const paper = promote(candidate);
		assert(paper, 'promote() should return a Paper');
		const fs = new InMemoryFileStore();
		const store = new PaperStore(fs);
		await store.upsert({ paper });
		assert(store.has(paper.sourceId), 'has() should report the paper stored');
		const got = await store.get(paper.sourceId);
		assert(got, 'get() should return the paper');
		assert(stable(got.embedding) === stable([0.6, 0.8]), `embedding vector not preserved: ${stable(got.embedding)}`);
		assert(stable(got) === stable(paper), 'end-to-end Paper round trip differs');
		// The vector must NOT have leaked into the human-facing note.
		const fm = parseNote(await firstMd(fs)).frontmatter;
		assert(!('embedding' in fm), 'embedding vector must never reach the note frontmatter');
	});

	// E2 [system] emergent cross-spec property: when 002 RE-collects/re-persists a paper it
	// already saved, the user's own note body (003 FR-005) must survive, while the managed
	// region reflects the fresh collection data. No single-spec test spans this: it needs
	// 002's re-persist meeting 003's user-region preservation.
	await check('E2', '[system] a 002 re-persist updates managed data yet preserves the user note body (FR-005)', async () => {
		const fs = new InMemoryFileStore();
		const store = new PaperStore(fs);
		const first = promote(enrichedCandidate());
		assert(first, 'promote() should return a Paper');
		await store.upsert({ paper: first });
		// The user edits the note, appending free-form notes after the managed region.
		const files = await fs.list();
		const mdPath = files.find((f) => f.endsWith('.md'));
		assert(mdPath, 'expected a note file');
		const edited = (await fs.read(mdPath)) + 'My own reading notes.';
		await fs.write(mdPath, edited);
		// 002 re-collects the same paper with a fresh (higher) citation count and re-persists.
		const refreshed = promote(enrichedCandidate({ citationCount: 99 }));
		assert(refreshed, 'promote() should return a Paper');
		await store.upsert({ paper: refreshed });
		const after = await fs.read(mdPath);
		assert(after !== null, 'note should still exist after the update');
		assert(after.includes('My own reading notes.'), 'user note body must be preserved across a 002 re-persist');
		assert(parseNote(after).frontmatter['citationCount'] === 99, 'managed frontmatter should reflect the refreshed citation count');
	});

	// ---- report --------------------------------------------------------------
	let passed = 0;
	let failed = 0;
	let skipped = 0;
	for (const r of results) {
		if (r.status === 'PASS') {
			passed++;
			console.log(`[PASS] ${r.id} — ${r.desc}`);
		} else if (r.status === 'FAIL') {
			failed++;
			console.log(`[FAIL] ${r.id} — ${r.desc}: ${r.error}`);
		} else {
			skipped++;
			console.log(`[SKIP] ${r.id} — ${r.desc} (${r.reason})`);
		}
	}
	console.log(`Summary: ${passed} passed, ${failed} failed, ${skipped} skipped`);
	process.exitCode = failed > 0 ? 1 : 0;
}

void main();

// Referenced to keep the import meaningful even if a scenario using it is edited out.
void toPaper;
