// Generated by /specs-chain-test for the chain:
//   001-core-data-models -> 002-subscription-paper-collection -> 003-paper-note-persistence
//
// Verifies the three specs as one pipeline, from both required angles: per-seam connection
// points (C<k>) and the whole-system flow threaded end-to-end (E<k>). Uses REAL exports on
// both sides of every seam — 001's toPaper/isValidPaper, 002's promote()/runCollectionPass
// pipeline, and 003's PaperStore — never a re-derived copy. Report-only; run via esbuild +
// node (the repo's no-test-runner convention).
//
// THE CHAIN.
//   001 defines the Paper/PaperCandidate contract and toPaper() (the promotion + hold-back
//       rule: a missing/NaN year is held back, unknown citations default to 0 with
//       citationsKnown=false).
//   002 collects: its parser emits 001 PaperCandidates, and runCollectionPass() year-gates,
//       dedups, enriches, then promote()s (= 001's toPaper) and hands each Paper to an
//       injected persist hook.
//   003 persists: PaperStore.upsert()/has()/get() are exactly what 002's PipelineHooks
//       inject, wrapping the 001 Paper into a record + note and reading it back.
//
// runCollectionPass takes an AsyncIterable<PaperCandidate> and an `enrich` function, so the
// whole 001->002->003 flow runs OFFLINE here: candidates are built in the exact shape 002's
// parseArxivEntry emits (citationCount/references/embedding undefined = "not known yet"), a
// stub enrich stands in for the Semantic Scholar call, and the persist hook is backed by a
// real 003 PaperStore over an in-memory FileStore.

// runCollectionPass yields to the event loop via window.setTimeout — shim window to the Node
// global (same approach as specs-test/002's _obsidian-shim) BEFORE the pipeline runs.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(globalThis as any).window = globalThis;

import {
	toPaper,
	isValidPaper,
	isPaperSourceId,
	type Paper,
	type PaperCandidate,
	type PaperSourceId,
} from '../../src/models/paper';
import { promote } from '../../src/collection/promotion';
import { runCollectionPass } from '../../src/collection/pipeline';
import type { EnrichmentOutcome, PipelineHooks } from '../../src/collection/types';
import { PaperStore } from '../../src/persistence/store';
import { InMemoryFileStore } from '../../src/persistence/filestore';
import { parseNote } from '../../src/persistence/note';

type Status = 'PASS' | 'FAIL' | 'SKIP';
interface Result {
	id: string;
	desc: string;
	status: Status;
	error?: string;
	reason?: string;
}
const results: Result[] = [];

function check(id: string, desc: string, fn: () => void | Promise<void>): Promise<void> {
	return Promise.resolve()
		.then(fn)
		.then(
			() => {
				results.push({ id, desc, status: 'PASS' });
			},
			(err: unknown) => {
				results.push({ id, desc, status: 'FAIL', error: err instanceof Error ? err.message : String(err) });
			},
		);
}
function skip(id: string, desc: string, reason: string): void {
	results.push({ id, desc, status: 'SKIP', reason });
}
function assert(cond: unknown, message: string): asserts cond {
	if (!cond) throw new Error(message);
}
function stable(value: unknown): string {
	return JSON.stringify(value, (_k, v) => {
		if (v && typeof v === 'object' && !Array.isArray(v)) {
			return Object.fromEntries(Object.entries(v as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)));
		}
		return v;
	});
}

// The exact shape 002's parseArxivEntry emits for an arXiv hit: a valid 001 PaperCandidate
// with citationCount/references/embedding all undefined ("not known yet").
function arxivCandidate(overrides: Partial<PaperCandidate> = {}): PaperCandidate {
	return {
		title: 'Attention Is All You Need',
		publicationYear: 2017,
		authors: ['Ashish Vaswani', 'Noam Shazeer'],
		citationCount: undefined,
		abstract: 'We propose the Transformer.',
		sourceId: 'arxiv:1706.03762',
		references: undefined,
		embedding: undefined,
		embeddingModel: undefined,
		embeddingSource: undefined,
		...overrides,
	};
}

const NOOP_ENRICH = async (): Promise<Map<PaperSourceId, EnrichmentOutcome>> => new Map();

async function* iterate(cands: PaperCandidate[]): AsyncIterable<PaperCandidate> {
	for (const c of cands) yield c;
}

// A PipelineHooks backed by a real 003 PaperStore — this object is the 002<->003 seam.
function storeHooks(store: PaperStore): PipelineHooks {
	return {
		persist: (paper, summary) =>
			store.upsert({ paper, summary: summary?.summary, futureDirections: summary?.futureDirections }),
		alreadyPersisted: async (sourceId) => store.has(sourceId),
	};
}

async function main(): Promise<void> {
	// ===== 001 -> 002 seams ===================================================

	// C1 [001->002 promote] 002's promote() defers to 001's toPaper: an arXiv-only candidate
	// (the shape parseArxivEntry emits) promotes to a VALID 001 Paper carrying the
	// unknown-vs-zero contract (citationCount 0, citationsKnown false).
	await check('C1', '[001->002 promote] promote() turns an arXiv-only 001 candidate into a valid Paper (citationsKnown=false)', () => {
		const paper = promote(arxivCandidate());
		assert(paper, 'promote() should return a Paper for a real-year candidate');
		assert(isValidPaper(paper), '001 must accept the promoted Paper');
		assert(paper.citationCount === 0 && paper.citationsKnown === false, 'arXiv-only promotion must be cc=0 / citationsKnown=false');
		assert(paper.references.length === 0, 'unknown references must default to []');
		assert(paper.embedding === null, 'unknown embedding must default to null (pending)');
	});

	// C2 [001->002 promote negative] 002 can never promote what 001 holds back: a
	// missing/NaN publicationYear yields undefined (the 001 hold-back rule).
	await check('C2', '[001->002 promote] a candidate 001 holds back (missing/NaN year) is never promoted by 002', () => {
		assert(promote(arxivCandidate({ publicationYear: undefined })) === undefined, 'missing year must hold back');
		assert(promote(arxivCandidate({ publicationYear: Number.NaN })) === undefined, 'NaN year must hold back');
	});

	// C3 [001->002 pipeline] 002's runCollectionPass year-gate (FR-011) honors 001's year
	// contract: a yearless candidate is DROPPED by the real pipeline and never persisted.
	await check('C3', '[001->002 pipeline] runCollectionPass drops a yearless candidate before it can reach persist', async () => {
		const fs = new InMemoryFileStore();
		const store = new PaperStore(fs);
		await runCollectionPass(
			iterate([arxivCandidate({ sourceId: 'arxiv:0000.00000', publicationYear: undefined })]),
			storeHooks(store),
			() => false,
			() => undefined,
			NOOP_ENRICH,
		);
		assert(store.has('arxiv:0000.00000') === false, 'yearless candidate must not be persisted');
		assert((await fs.list()).length === 0, 'no files should be written for a fully year-gated batch');
	});

	// ===== 002 -> 003 seams ===================================================

	// C4 [002->003 hooks] 003's PaperStore structurally satisfies 002's injected
	// PipelineHooks.persist/alreadyPersisted (that this compiles is the cross-spec proof).
	await check('C4', '[002->003 hooks] PaperStore satisfies 002 PipelineHooks.persist/alreadyPersisted', async () => {
		const store = new PaperStore(new InMemoryFileStore());
		const hooks = storeHooks(store);
		const paper = promote(arxivCandidate());
		assert(paper, 'promote() should return a Paper');
		assert((await hooks.alreadyPersisted(paper.sourceId)) === false, 'not persisted before hooks.persist');
		await hooks.persist(paper);
		assert((await hooks.alreadyPersisted(paper.sourceId)) === true, 'persisted after hooks.persist');
	});

	// C5 [002->003 note] the note frontmatter mirrors the FR-002 shared subset of the
	// promoted 001 Paper.
	await check('C5', '[002->003 note] note frontmatter mirrors the promoted Paper subset', async () => {
		const paper = promote(arxivCandidate());
		assert(paper, 'promote() should return a Paper');
		const fs = new InMemoryFileStore();
		await new PaperStore(fs).upsert({ paper });
		const md = (await fs.list()).find((f) => f.endsWith('.md'));
		assert(md, 'a note should be written');
		const fm = parseNote((await fs.read(md)) ?? '').frontmatter;
		assert(fm['title'] === paper.title, 'title mismatch');
		assert(fm['publicationYear'] === paper.publicationYear, 'publicationYear mismatch');
		assert(fm['citationCount'] === paper.citationCount, 'citationCount mismatch');
		assert(fm['pg3d_sourceId'] === paper.sourceId, 'sourceId mismatch');
	});

	// C6 [002->003 note negative] fields outside the mirrored subset never leak into the note.
	await check('C6', '[002->003 note] references/embedding/schemaVersion do not leak into frontmatter', async () => {
		const paper = promote(arxivCandidate({ citationCount: 5, references: ['arxiv:1409.0473'], embedding: [0.6, 0.8], embeddingModel: 'm', embeddingSource: 'local' }));
		assert(paper, 'promote() should return a Paper');
		const fs = new InMemoryFileStore();
		await new PaperStore(fs).upsert({ paper });
		const md = (await fs.list()).find((f) => f.endsWith('.md'));
		assert(md, 'a note should be written');
		const fm = parseNote((await fs.read(md)) ?? '').frontmatter;
		for (const leaked of ['references', 'embedding', 'embeddingModel', 'schemaVersion', 'abstract', 'createdAt']) {
			assert(!(leaked in fm), `frontmatter must not carry '${leaked}'`);
		}
	});

	// SKIP [001->002 parse] parseArxivEntry/parseArxivAtom emit 001 candidates from arXiv XML,
	// but they need a DOM (DOMParser / Element). @xmldom/xmldom is not installed in this
	// environment, so the parser half of the 001<->002 seam is exercised via the exact
	// candidate shape it emits (above) rather than by running the parser itself.
	skip('C7', '[001->002 parse] parseArxivAtom emits valid 001 candidates from arXiv XML', '@xmldom/xmldom devDependency not installed; DOM unavailable offline');

	// ===== Whole-system end-to-end (001 -> 002 -> 003) ========================

	// E1 [system] a mixed batch threaded through the REAL 002 pipeline into a REAL 003 store:
	//   - an enriched paper (stub enrich supplies a Semantic Scholar count) -> citationsKnown TRUE
	//   - an arXiv-only paper -> citationsKnown FALSE, cc 0
	//   - a yearless paper -> DROPPED by the FR-011 gate
	//   - a duplicate sourceId -> DROPPED by the FR-009 dedup
	// Then every survivor is read back through 003 and must equal what 001's toPaper produces
	// from the same (post-enrichment) candidate. This asserts emergent properties no single
	// seam or single-spec test catches: gate + dedup + enrich-apply + promote + persist all
	// cooperating as one pipeline.
	await check('E1', '[system] mixed candidate batch -> runCollectionPass(002) -> PaperStore(003) round-trips with gate/dedup/enrich all honored', async () => {
		const ENRICHED: PaperSourceId = 'arxiv:1706.03762';
		const ARXIV_ONLY: PaperSourceId = 'arxiv:1409.0473';
		const batch: PaperCandidate[] = [
			arxivCandidate({ sourceId: ENRICHED, publicationYear: 2017 }),
			arxivCandidate({ sourceId: ARXIV_ONLY, publicationYear: 2014, title: 'Neural MT by Jointly Learning' }),
			arxivCandidate({ sourceId: 'arxiv:bad', publicationYear: undefined }), // year-gated
			arxivCandidate({ sourceId: ENRICHED, publicationYear: 2017 }), // duplicate -> deduped
		];
		const enrich = async (): Promise<Map<PaperSourceId, EnrichmentOutcome>> => {
			const m = new Map<PaperSourceId, EnrichmentOutcome>();
			m.set(ENRICHED, { status: 'enriched', citationCount: 42, references: [ARXIV_ONLY] });
			return m;
		};

		const fs = new InMemoryFileStore();
		const store = new PaperStore(fs);
		await runCollectionPass(iterate(batch), storeHooks(store), () => false, () => undefined, enrich);

		// Survivors: exactly the enriched + the arXiv-only paper.
		assert(store.has(ENRICHED), 'enriched paper should be persisted');
		assert(store.has(ARXIV_ONLY), 'arXiv-only paper should be persisted');
		assert(store.has('arxiv:bad') === false, 'yearless paper must be dropped');
		const all: Paper[] = [];
		for await (const p of store.all()) all.push(p);
		assert(all.length === 2, `exactly 2 papers should survive (gate+dedup), got ${all.length}`);

		// The enriched survivor equals toPaper() of the post-enrichment candidate — proving
		// 002's enrich-then-promote produced precisely 001's promotion of the enriched shape.
		const expectedEnriched = toPaper(arxivCandidate({ sourceId: ENRICHED, publicationYear: 2017, citationCount: 42, references: [ARXIV_ONLY] }));
		assert(expectedEnriched, 'control toPaper() should succeed');
		const gotEnriched = await store.get(ENRICHED);
		assert(gotEnriched, 'enriched paper should read back');
		assert(gotEnriched.citationsKnown === true && gotEnriched.citationCount === 42, 'enriched paper must carry citationsKnown=true / cc=42');
		assert(stable(gotEnriched.references) === stable([ARXIV_ONLY]), 'enriched references must survive');
		assert(stable(gotEnriched) === stable(expectedEnriched), 'enriched round trip must equal 001 toPaper() of the enriched candidate');

		// The arXiv-only survivor keeps the unknown-vs-zero distinction end to end.
		const gotArxiv = await store.get(ARXIV_ONLY);
		assert(gotArxiv, 'arXiv-only paper should read back');
		assert(gotArxiv.citationsKnown === false && gotArxiv.citationCount === 0, 'arXiv-only paper must stay unknown (cc 0 / citationsKnown false) through the whole pipeline');
	});

	// E2 [system] the same flow starting one seam earlier — arXiv XML parsed by 002's
	// parseArxivAtom into 001 candidates, then through the pipeline into 003 — is SKIP: it
	// needs @xmldom/xmldom (see C7). E1 asserts the longest offline-exercisable prefix
	// (candidate -> pipeline -> store), so only the XML front-door is unverified here.
	skip('E2', '[system] arXiv XML -> parseArxivAtom(002) -> runCollectionPass -> PaperStore, full front-to-back', '@xmldom/xmldom devDependency not installed; XML front-door not exercisable offline');

	// keep the import meaningful independent of which scenarios reference it
	void isPaperSourceId;

	// ===== report =============================================================
	let passed = 0;
	let failed = 0;
	let skipped = 0;
	for (const r of results) {
		if (r.status === 'PASS') {
			passed++;
			console.log(`[PASS] ${r.id} — ${r.desc}`);
		} else if (r.status === 'FAIL') {
			failed++;
			console.log(`[FAIL] ${r.id} — ${r.desc}: ${r.error}`);
		} else {
			skipped++;
			console.log(`[SKIP] ${r.id} — ${r.desc} (${r.reason})`);
		}
	}
	console.log(`Summary: ${passed} passed, ${failed} failed, ${skipped} skipped`);
	process.exitCode = failed > 0 ? 1 : 0;
}

void main();
