// Generated by /specs-chain-test for the FULL chain:
//   001-core-data-models → 002-subscription-paper-collection →
//   003-paper-note-persistence → 004-paper-summarization → 005-manual-paper-refresh
//
// Verifies how all five specs INTEGRATE (per-seam connection points + one whole-system
// end-to-end flow), not each in isolation. This extends the existing 001+002+003+005
// chain by threading 004's summarization seam through the middle: 002's collection pass
// (and 005's refresh) drive 004's REAL createSummarizeHook, whose SummaryResult is then
// persisted by 003 into the note's managed body.
//
// Runs against the real src/ exports via esbuild + node with 'obsidian' aliased to a
// programmable requestUrl shim + a DOMParser polyfill, so the 002 enrichment leg and the
// 005 refresh leg run their real client/parser code with deterministic inputs and zero
// live network. The summarization PROVIDER (004's single external boundary) is an
// in-process fake behind the real SummarizationProvider interface — exactly the seam the
// spec stubs — while 004's hook gating (createSummarizeHook + isUncited + runGeneration)
// is the real code under test. Report-only (does not modify src/).

import type { EntrySpec } from './_obsidian-shim';

// --- polyfills (used at call time) ---------------------------------------------------
function makeEntryElement(spec: EntrySpec): unknown {
	const node = (t?: string) => (t === undefined ? [] : [{ textContent: t }]);
	const authorNodes = (spec.authors ?? []).map((name) => ({
		getElementsByTagName: (t: string) => (t === 'name' ? [{ textContent: name }] : []),
	}));
	const map: Record<string, unknown[]> = {
		id: node(spec.id), title: node(spec.title), summary: node(spec.summary),
		published: node(spec.published), author: authorNodes,
	};
	return { getElementsByTagName: (t: string) => map[t] ?? [] };
}
class FakeDOMParser {
	parseFromString(text: string): unknown {
		const data = JSON.parse(text) as { entries: EntrySpec[] };
		const entries = data.entries.map(makeEntryElement);
		return { getElementsByTagName: (t: string) => (t === 'entry' ? entries : []) };
	}
}
/* eslint-disable @typescript-eslint/no-explicit-any */
(globalThis as any).window = globalThis;
(globalThis as any).DOMParser = FakeDOMParser;
/* eslint-enable @typescript-eslint/no-explicit-any */

// 001 — core data models
import type { Paper, PaperCandidate, PaperSourceId } from '../../src/models/paper';
import { isValidPaper, toPaper } from '../../src/models/paper';
// 002 — collection (promotion, embedding, S2 parse, real pipeline)
import { promote } from '../../src/collection/promotion';
import { computeBaselineEmbedding, BASELINE_EMBEDDING_MODEL } from '../../src/collection/embedding';
import { parseSemanticScholarPaper, toPaperSourceId } from '../../src/collection/semanticScholarParser';
import { runCollectionPass } from '../../src/collection/pipeline';
import type { PipelineHooks, SummaryResult, SummarizationInput } from '../../src/collection/types';
// 003 — persistence
import { PaperStore } from '../../src/persistence/store';
import { InMemoryFileStore } from '../../src/persistence/filestore';
import { parseNote } from '../../src/persistence/note';
// 004 — summarization (real hook + gating; provider is the stubbed boundary)
import { createSummarizeHook } from '../../src/services/summarization/hook';
import { isUncited } from '../../src/services/summarization/isUncited';
import { MIN_GENERATED_TEXT_LENGTH } from '../../src/services/summarization/constants';
import type { SummarizationProvider } from '../../src/services/summarization/types';
// 005 — refresh
import { createConcurrencyGuard } from '../../src/refresh/concurrencyGuard';
import { refreshOne } from '../../src/refresh/refreshOne';
import type { RefreshHooks } from '../../src/refresh/types';

type Status = 'PASS' | 'FAIL' | 'SKIP';
interface Result { id: string; desc: string; status: Status; note?: string }
const results: Result[] = [];
function report(r: Result): void {
	results.push(r);
	if (r.status === 'PASS') console.log(`[PASS] ${r.id} — ${r.desc}`);
	else if (r.status === 'FAIL') console.log(`[FAIL] ${r.id} — ${r.desc}: ${r.note}`);
	else console.log(`[SKIP] ${r.id} — ${r.desc} (${r.note})`);
}
async function check(id: string, desc: string, fn: () => void | Promise<void>): Promise<void> {
	try { await fn(); report({ id, desc, status: 'PASS' }); }
	catch (e) { report({ id, desc, status: 'FAIL', note: (e as Error).message }); }
}
function skip(id: string, desc: string, reason: string): void { report({ id, desc, status: 'SKIP', note: reason }); }
function assert(cond: boolean, msg: string): void { if (!cond) throw new Error(msg); }
function eqArr(a: readonly number[] | null, b: readonly number[] | null): boolean {
	if (a === null || b === null) return a === b;
	return a.length === b.length && a.every((v, i) => v === b[i]);
}

// --- deterministic provider fakes (004's external boundary) --------------------------
// Real 004 hook logic runs; only the network call is replaced. The summary EMBEDS the
// input abstract so a regenerated summary is observably tied to the current content —
// which is exactly what lets the 004→003 and 004→005 seam assertions prove the new
// abstract flowed all the way into the note rather than a stale one lingering.
const pad = (s: string) => s.padEnd(MIN_GENERATED_TEXT_LENGTH + 40, ' .');
interface SpyProvider extends SummarizationProvider { calls: SummarizationInput[] }
function fakeProvider(id = 'fake'): SpyProvider {
	const calls: SummarizationInput[] = [];
	return {
		id,
		calls,
		async generate(input: SummarizationInput): Promise<{ summary: string; futureDirections?: string }> {
			calls.push(input);
			return {
				summary: pad(`SUMMARY[${input.title}] ${input.abstract}`),
				futureDirections: pad(`FUTURE work extending ${input.title}`),
			};
		},
	};
}
function hookFor(provider: SummarizationProvider | undefined, credential: string | undefined = 'key') {
	const problems: string[] = [];
	const summarize = createSummarizeHook({
		getProvider: () => provider,
		getCredential: () => credential,
		notifyCredentialProblem: (m) => problems.push(m),
	});
	return { summarize, problems };
}

interface Api {
	arxiv: Map<string, EntrySpec | 'notfound' | 'throw'>;
	s2: Map<string, { citationCount: number; references?: unknown[] } | '404' | 'null'>;
	counts: { arxiv: number; s2single: number; s2batch: number };
}
function resetApi(): Api {
	const a: Api = { arxiv: new Map(), s2: new Map(), counts: { arxiv: 0, s2single: 0, s2batch: 0 } };
	(globalThis as unknown as { __api: Api }).__api = a;
	return a;
}
const YEAR = new Date().getFullYear();
const SID = 'arxiv:2301.77777' as PaperSourceId;
function baseOf(sid: PaperSourceId): string { return sid.slice(sid.indexOf(':') + 1); }

function candidate(over: Partial<PaperCandidate> = {}): PaperCandidate {
	return {
		title: 'Head Title', publicationYear: YEAR, authors: ['Ada'], citationCount: undefined,
		abstract: 'Head Abstract', sourceId: SID, references: undefined,
		embedding: undefined, embeddingModel: undefined, embeddingSource: undefined, ...over,
	};
}
function embed(p: Paper): Paper {
	const e = computeBaselineEmbedding(p.title, p.abstract);
	p.embedding = e.embedding; p.embeddingModel = e.embeddingModel; p.embeddingSource = e.embeddingSource;
	return p;
}
function newStore(): { store: PaperStore; fs: InMemoryFileStore } {
	const fs = new InMemoryFileStore();
	return { store: new PaperStore(fs), fs };
}
function arxivEntry(id: string, over: Partial<EntrySpec> = {}): EntrySpec {
	return { id: `http://arxiv.org/abs/${id}v1`, title: 'Head Title', summary: 'Head Abstract', published: `${YEAR}-01-01`, authors: ['Ada'], ...over };
}
async function findMd(fs: InMemoryFileStore, sid: string): Promise<string> {
	for (const f of await fs.list()) if (f.endsWith('.md')) { const t = await fs.read(f); if (t?.includes(sid)) return f; }
	throw new Error(`no .md for ${sid}`);
}
async function managedBodyOf(fs: InMemoryFileStore, sid: string): Promise<string> {
	return parseNote((await fs.read(await findMd(fs, sid))) as string).managedBody;
}
const noEnrich = async (): Promise<Map<PaperSourceId, import('../../src/collection/types').EnrichmentOutcome>> => new Map();

async function main(): Promise<void> {
	// ============ Seam 001 → 002 ============
	await check('C1', '[001→002] promote() lifts a candidate to a 001-valid Paper; citationsKnown mirrors enrichment', () => {
		const enriched = promote(candidate({ citationCount: 7, references: ['arxiv:1900.00001' as PaperSourceId] }));
		assert(enriched !== undefined && isValidPaper(enriched), 'enriched candidate promotes to a valid Paper');
		assert(enriched!.citationCount === 7 && enriched!.citationsKnown === true, 'known citations carried, citationsKnown true');
		const bare = promote(candidate({ citationCount: undefined }));
		assert(bare !== undefined && isValidPaper(bare), 'un-enriched candidate still promotes');
		assert(bare!.citationCount === 0 && bare!.citationsKnown === false, 'un-enriched → count 0, citationsKnown false (001/002 FR-018)');
	});

	await check('C2', '[001→002 negative] a candidate 001 rejects (missing/NaN year) never promotes — nothing can flow downstream', () => {
		assert(promote(candidate({ publicationYear: undefined })) === undefined, 'undefined year held back');
		assert(promote(candidate({ publicationYear: Number.NaN })) === undefined, 'NaN year held back');
		assert(toPaper(candidate({ publicationYear: undefined })) === undefined, '001 toPaper agrees (producer side)');
	});

	await check('C3', "[002→001 embedding] 002's baseline embedding produces a 001-valid embedded Paper (pending null also valid)", () => {
		const p = embed(promote(candidate())!);
		assert(isValidPaper(p), '002-embedded Paper satisfies 001 isValidPaper');
		assert(Array.isArray(p.embedding) && p.embedding!.length === 2048, 'embedding is a 2048-dim numeric vector');
		assert(p.embeddingModel === BASELINE_EMBEDDING_MODEL && p.embeddingSource === 'local', 'model/source set per 002 FR-044');
		const pending = promote(candidate())!;
		assert(isValidPaper(pending) && pending.embedding === null, 'pending (null) embedding is still 001-valid (001 FR-021)');
	});

	// ============ Seam 002/001 → 003 ============
	await check('C4', '[002/001→003] a promoted+embedded Paper round-trips through 003 store; note frontmatter mirrors the shared subset', async () => {
		resetApi(); const { store, fs } = newStore();
		const p = embed(promote(candidate({ citationCount: 4, references: ['arxiv:1800.00002' as PaperSourceId] }))!);
		await store.upsert({ paper: p });
		const round = (await store.get(SID))!;
		assert(JSON.stringify(round) === JSON.stringify(p), '003 get() round-trips the exact 001 Paper');
		const fm = parseNote((await fs.read(await findMd(fs, SID))) as string).frontmatter;
		assert(fm['title'] === p.title, 'frontmatter title mirrors Paper');
		assert(JSON.stringify(fm['authors']) === JSON.stringify(p.authors), 'frontmatter authors mirror Paper');
		assert(fm['publicationYear'] === p.publicationYear, 'frontmatter publicationYear mirrors Paper');
		assert(fm['citationCount'] === p.citationCount, 'frontmatter citationCount mirrors Paper');
		assert(fm['pg3d_sourceId'] === p.sourceId, 'frontmatter pg3d_sourceId mirrors Paper');
	});

	await check('C5', '[001/002→003 negative] fields OUTSIDE the shared subset do not leak into the note frontmatter (003 FR-002)', async () => {
		resetApi(); const { store, fs } = newStore();
		const p = embed(promote(candidate({ citationCount: 4, references: ['arxiv:1800.00002' as PaperSourceId] }))!);
		await store.upsert({ paper: p });
		const fm = parseNote((await fs.read(await findMd(fs, SID))) as string).frontmatter;
		for (const leaked of ['schemaVersion', 'createdAt', 'updatedAt', 'embedding', 'embeddingModel', 'embeddingSource', 'abstract']) {
			assert(!(leaked in fm), `frontmatter must not carry '${leaked}'`);
		}
		assert(Array.isArray(fm['references']) && (fm['references'] as string[])[0] === 'arxiv:1800.00002', 'references (cited papers) mirrored into frontmatter (FR-002 amended)');
	});

	// ============ Seam 002 → 004 (collection drives the summarize hook) ============
	await check('C6', "[002→004] 002's pipeline drives 004's createSummarizeHook with EXACTLY the 4-field SummarizationInput — no full Paper leaks across the seam", async () => {
		resetApi(); const { store } = newStore();
		const spy = fakeProvider();
		const { summarize } = hookFor(spy);
		const hooks: PipelineHooks = {
			summarize,
			persist: async (paper, summary) => store.upsert({ paper, summary: summary?.summary, futureDirections: summary?.futureDirections }),
			alreadyPersisted: async (sid) => store.has(sid),
		};
		async function* one(): AsyncIterable<PaperCandidate> { yield candidate(); }
		await runCollectionPass(one(), 'keyword:test', hooks, () => true, () => undefined, noEnrich, () => undefined as never);
		assert(spy.calls.length === 1, 'the 004 provider was driven exactly once by 002');
		const keys = Object.keys(spy.calls[0]!).sort();
		assert(JSON.stringify(keys) === JSON.stringify(['abstract', 'citationCount', 'citationsKnown', 'title']), `only the 4 minimized fields crossed the seam (got ${keys.join(',')})`);
		for (const forbidden of ['sourceId', 'references', 'embedding', 'publicationYear', 'authors']) {
			assert(!(forbidden in spy.calls[0]!), `'${forbidden}' must never reach the summarization provider (data minimization, 002 Decision 22)`);
		}
	});

	await check('C7', "[002→004 gating] 004's isUncited gate — confirmed-uncited yields future-directions; a cited paper yields '' — as reached through the real hook", async () => {
		const uncited: SummarizationInput = { title: 'T', abstract: 'A meaningful abstract body.', citationCount: 0, citationsKnown: true };
		const cited: SummarizationInput = { title: 'T', abstract: 'A meaningful abstract body.', citationCount: 12, citationsKnown: true };
		const unknownZero: SummarizationInput = { title: 'T', abstract: 'A meaningful abstract body.', citationCount: 0, citationsKnown: false };
		assert(isUncited(uncited) && !isUncited(cited) && !isUncited(unknownZero), '004 isUncited: confirmed-zero only');
		const { summarize } = hookFor(fakeProvider());
		const u = await summarize(uncited);
		const c = await summarize(cited);
		assert(u !== undefined && u.futureDirections.length > 0, 'confirmed-uncited paper gets non-empty future-directions through the hook');
		assert(c !== undefined && c.futureDirections === '', "cited paper's future-directions degrade to '' through the hook (research.md §2)");
	});

	await check('C8', '[002→004 negative] an unconfigured provider or empty credential yields undefined and never calls the provider (abstract fallback upstream)', async () => {
		const { summarize: noProvider } = hookFor(undefined);
		assert((await noProvider({ title: 'T', abstract: 'A body long enough.', citationCount: 1, citationsKnown: true })) === undefined, 'unconfigured provider → undefined');
		const spy = fakeProvider();
		const { summarize: emptyCred } = hookFor(spy, '   ');
		assert((await emptyCred({ title: 'T', abstract: 'A body long enough.', citationCount: 1, citationsKnown: true })) === undefined, 'blank credential → undefined');
		assert(spy.calls.length === 0, 'the provider.generate boundary was never crossed');
	});

	// ============ Seam 004 → 003 (summary lands in the note) ============
	await check('C9', "[004→003] a SummaryResult persisted through 003 replaces the abstract in the note's managed body and appends a Future directions section — never in frontmatter or user body", async () => {
		resetApi(); const { store, fs } = newStore();
		const spy = fakeProvider();
		const { summarize } = hookFor(spy);
		// Confirmed-uncited so future-directions is produced.
		const hooks: PipelineHooks = {
			summarize,
			persist: async (paper, summary) => store.upsert({ paper, summary: summary?.summary, futureDirections: summary?.futureDirections }),
			alreadyPersisted: async (sid) => store.has(sid),
		};
		const enrichUncited = async (): Promise<Map<PaperSourceId, import('../../src/collection/types').EnrichmentOutcome>> =>
			new Map([[SID, { status: 'enriched', citationCount: 0, references: [] }]]);
		async function* one(): AsyncIterable<PaperCandidate> { yield candidate(); }
		await runCollectionPass(one(), 'keyword:test', hooks, () => true, () => undefined, enrichUncited, () => undefined as never);
		const body = await managedBodyOf(fs, SID);
		assert(body.includes('SUMMARY[Head Title]'), 'the 004 summary (not the raw abstract) is the managed-body prose');
		assert(body.includes('## Future directions'), 'a Future directions section is rendered for the confirmed-uncited paper');
		assert(body.includes('FUTURE work extending'), 'the future-directions text lands in the managed body');
		const fm = parseNote((await fs.read(await findMd(fs, SID))) as string).frontmatter;
		assert(!('summary' in fm) && !('futureDirections' in fm), 'generated text never leaks into the frontmatter');
		const userBody = parseNote((await fs.read(await findMd(fs, SID))) as string).userBody;
		assert(userBody.trim() === '', 'generated text stays in the managed region, not the user body');
	});

	await check('C10', "[004→003 negative] with no summary (unconfigured provider) the managed body falls back to the abstract; a cited paper's note carries no Future directions section", async () => {
		resetApi(); const { store, fs } = newStore();
		// (a) Unconfigured provider → persist summary undefined → abstract fallback in the note.
		const { summarize: noProvider } = hookFor(undefined);
		const hooksNone: PipelineHooks = {
			summarize: noProvider,
			persist: async (paper, summary) => store.upsert({ paper, summary: summary?.summary, futureDirections: summary?.futureDirections }),
			alreadyPersisted: async (sid) => store.has(sid),
		};
		async function* one(): AsyncIterable<PaperCandidate> { yield candidate(); }
		await runCollectionPass(one(), 'keyword:test', hooksNone, () => true, () => undefined, noEnrich, () => undefined as never);
		const bodyA = await managedBodyOf(fs, SID);
		assert(bodyA.trim() === 'Head Abstract', 'no summary → managed body is exactly the abstract (fallback)');
		assert(!bodyA.includes('## Future directions'), 'no future-directions section without a generated one');

		// (b) A CITED paper summarized → summary present but future-directions degraded to '' → no section.
		resetApi(); const { store: store2, fs: fs2 } = newStore();
		const { summarize } = hookFor(fakeProvider());
		const hooksCited: PipelineHooks = {
			summarize,
			persist: async (paper, summary) => store2.upsert({ paper, summary: summary?.summary, futureDirections: summary?.futureDirections }),
			alreadyPersisted: async (sid) => store2.has(sid),
		};
		const enrichCited = async (): Promise<Map<PaperSourceId, import('../../src/collection/types').EnrichmentOutcome>> =>
			new Map([[SID, { status: 'enriched', citationCount: 40, references: [] }]]);
		async function* one2(): AsyncIterable<PaperCandidate> { yield candidate(); }
		await runCollectionPass(one2(), 'keyword:test', hooksCited, () => true, () => undefined, enrichCited, () => undefined as never);
		const bodyB = await managedBodyOf(fs2, SID);
		assert(bodyB.includes('SUMMARY[Head Title]'), 'cited paper still gets a summary');
		assert(!bodyB.includes('## Future directions'), 'a cited paper renders no Future directions section');
	});

	// ============ Seam 002 → 005 ============
	await check('C11', "[002→005] a content-changing refresh recomputes the embedding via 002's computeBaselineEmbedding", async () => {
		const a = resetApi(); const { store } = newStore();
		await store.upsert({ paper: embed(promote(candidate())!) });
		a.arxiv.set(baseOf(SID), arxivEntry(baseOf(SID), { summary: 'Revised Abstract' }));
		a.s2.set(baseOf(SID), { citationCount: 2, references: [] });
		await refreshOne(store, SID, createConcurrencyGuard(), {}, () => false, () => undefined, () => ({ provider: 'bundled' }) as never);
		const after = (await store.get(SID))!;
		assert(eqArr(after.embedding, computeBaselineEmbedding('Head Title', 'Revised Abstract').embedding), "005's recomputed embedding == 002's baseline of the new content");
		assert(after.embeddingModel === BASELINE_EMBEDDING_MODEL, 'embedding model still 002 baseline');
	});

	await check('C12', "[002→005] a single refresh applies citations parsed by 002's parseSemanticScholarPaper/toPaperSourceId (version-stripped)", async () => {
		const a = resetApi(); const { store } = newStore();
		await store.upsert({ paper: embed(promote(candidate())!) });
		const s2body = { citationCount: 33, references: [{ paperId: 'x', externalIds: { ArXiv: '1700.00003v2' } }] };
		a.arxiv.set(baseOf(SID), arxivEntry(baseOf(SID)));
		a.s2.set(baseOf(SID), s2body);
		await refreshOne(store, SID, createConcurrencyGuard(), {}, () => false, () => undefined, () => ({ provider: 'bundled' }) as never);
		const after = (await store.get(SID))!;
		const parsed = parseSemanticScholarPaper(s2body);
		assert(after.citationCount === parsed.citationCount && after.citationCount === 33, 'citation count applied via 002 parser');
		assert(after.references.length === 1 && after.references[0] === toPaperSourceId(parsed.references[0]!), 'reference sourceId built via 002 toPaperSourceId');
		assert(after.references[0] === 'arxiv:1700.00003', 'arXiv version suffix stripped across the seam');
	});

	// ============ Seam 004 → 005 (refresh regenerates the summary) ============
	await check('C13', "[004→005] a content-changing refresh regenerates the summary via 004's hook and 003 lands the new summary (reflecting the new abstract) in the note", async () => {
		const a = resetApi(); const { store, fs } = newStore();
		// Seed with an initial 004-generated summary via a collection pass.
		const { summarize } = hookFor(fakeProvider());
		const hooks: PipelineHooks = {
			summarize,
			persist: async (paper, summary) => store.upsert({ paper, summary: summary?.summary, futureDirections: summary?.futureDirections }),
			alreadyPersisted: async (sid) => store.has(sid),
		};
		async function* one(): AsyncIterable<PaperCandidate> { yield candidate(); }
		await runCollectionPass(one(), 'keyword:test', hooks, () => true, () => undefined, noEnrich, () => undefined as never);
		assert((await managedBodyOf(fs, SID)).includes('Head Abstract'), 'seed summary embeds the original abstract');

		// Refresh with a NEW abstract; summarization enabled → 004 regenerates through refresh.
		a.arxiv.set(baseOf(SID), arxivEntry(baseOf(SID), { summary: 'Refreshed Abstract Body' }));
		a.s2.set(baseOf(SID), { citationCount: 3, references: [] });
		const refreshHooks: RefreshHooks = { summarize };
		const out = await refreshOne(store, SID, createConcurrencyGuard(), refreshHooks, () => true, () => undefined, () => ({ provider: 'bundled' }) as never);
		assert(out.status === 'updated', 'refresh completed');
		const body = await managedBodyOf(fs, SID);
		assert(body.includes('SUMMARY[Head Title]') && body.includes('Refreshed Abstract Body'), 'regenerated summary reflects the NEW abstract across 004→005→003');
		assert(!body.includes('Head Abstract'), 'the stale summary (old abstract) was replaced, not merged');
	});

	await check('C14', '[004→005 negative] with summarization disabled, a content-changing refresh leaves the stored summary untouched (003 field-scoped merge)', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		await store.upsert({ paper: embed(promote(candidate())!), summary: 'ORIGINAL SUMMARY kept verbatim across a disabled refresh' });
		assert((await managedBodyOf(fs, SID)).includes('ORIGINAL SUMMARY'), 'seed summary present');
		a.arxiv.set(baseOf(SID), arxivEntry(baseOf(SID), { summary: 'A Changed Abstract' }));
		a.s2.set(baseOf(SID), { citationCount: 1, references: [] });
		const spy = fakeProvider();
		const out = await refreshOne(store, SID, createConcurrencyGuard(), { summarize: hookFor(spy).summarize }, () => false, () => undefined, () => ({ provider: 'bundled' }) as never);
		assert(out.status === 'updated', 'refresh still updates content');
		assert(spy.calls.length === 0, 'the 004 provider is never invoked while summarization is disabled');
		assert((await store.get(SID))!.abstract === 'A Changed Abstract', 'content still refreshed');
		assert((await managedBodyOf(fs, SID)).includes('ORIGINAL SUMMARY'), 'the stored summary survived the disabled refresh');
	});

	// ============ Seam 003 → 005 ============
	await check('C15', '[003→005] refresh reads via 003 get() and writes via 003 upsert(); the user-owned note body is preserved', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		await store.upsert({ paper: embed(promote(candidate())!) });
		const md = await findMd(fs, SID);
		await fs.write(md, (await fs.read(md))! + 'MY OWN NOTES\n');
		a.arxiv.set(baseOf(SID), arxivEntry(baseOf(SID), { summary: 'Newer Abstract' }));
		a.s2.set(baseOf(SID), { citationCount: 1, references: [] });
		const out = await refreshOne(store, SID, createConcurrencyGuard(), {}, () => false, () => undefined, () => ({ provider: 'bundled' }) as never);
		assert(out.status === 'updated', 'refresh completes through the 003 store');
		assert((await store.get(SID))!.abstract === 'Newer Abstract', 'updated Paper read back through 003 get()');
		assert((await fs.read(md))!.includes('MY OWN NOTES'), 'user body preserved across the 003↔005 seam');
	});

	await check('C16', '[003→005 negative] refresh of a sourceId absent from the 003 store makes no provider call and writes nothing', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		const before = (await fs.list()).length;
		const out = await refreshOne(store, 'arxiv:0000.00000' as PaperSourceId, createConcurrencyGuard(), {}, () => false, () => undefined, () => ({ provider: 'bundled' }) as never);
		assert(out.status === 'notFound', 'absent sourceId → notFound');
		assert(a.counts.arxiv === 0 && a.counts.s2single === 0, 'no provider call crossed the seam');
		assert((await fs.list()).length === before, 'store untouched');
	});

	// ============ Whole-system end-to-end (all five specs) ============
	await check('E1', '[system] candidate → REAL 002 pipeline + REAL 004 summarize → 003 note → 005 refresh regenerates → 003 read-back stays 001-valid, note reflects the new summary, user body intact', async () => {
		const a = resetApi(); const { store, fs } = newStore();
		// Head: enrichment returns a CONFIRMED-uncited count (0) so 004 also generates future-directions.
		a.s2.set(baseOf(SID), { citationCount: 0, references: [] });
		const { summarize } = hookFor(fakeProvider());
		const hooks: PipelineHooks = {
			summarize,
			persist: async (paper: Paper, summary?: SummaryResult) => store.upsert({ paper, summary: summary?.summary, futureDirections: summary?.futureDirections }),
			alreadyPersisted: async (sid: PaperSourceId) => store.has(sid),
		};
		async function* candidates(): AsyncIterable<PaperCandidate> { yield candidate(); }
		// Drive the REAL 002 pipeline: dedup → batched enrich (shim) → promote (001) →
		// baseline embedding (002 FR-044) → 004 summarize hook → persist (003). Summarization ON.
		await runCollectionPass(candidates(), 'keyword:test', hooks, () => true, () => undefined, undefined, () => undefined as never);

		const collected = await store.get(SID);
		assert(collected !== undefined && isValidPaper(collected), 'collected Paper is present and 001-valid');
		assert(collected!.citationCount === 0 && collected!.citationsKnown === true, 'confirmed-uncited threaded through promotion');
		assert(eqArr(collected!.embedding, computeBaselineEmbedding('Head Title', 'Head Abstract').embedding), 'baseline embedding attached at collection');
		let body = await managedBodyOf(fs, SID);
		assert(body.includes('SUMMARY[Head Title] Head Abstract'), '004 summary (over the original abstract) landed in the note at collection');
		assert(body.includes('## Future directions'), 'confirmed-uncited paper got a Future directions section');

		const mdPath = await findMd(fs, SID);
		await fs.write(mdPath, (await fs.read(mdPath))! + 'USER TAIL\n'); // user writes in the note

		// Tail: 005 refresh with a newer arXiv revision (changed abstract) + higher (cited) citations.
		a.arxiv.set(baseOf(SID), arxivEntry(baseOf(SID), { title: 'Head Title', summary: 'End-to-end Revised Abstract' }));
		a.s2.set(baseOf(SID), { citationCount: 21, references: [] });
		const out = await refreshOne(store, SID, createConcurrencyGuard(), { summarize }, () => true, () => undefined, () => ({ provider: 'bundled' }) as never);
		assert(out.status === 'updated', 'refresh completes end-to-end');

		// Emergent, whole-chain invariants no single seam/spec test alone would catch:
		const final = (await store.get(SID))!;
		assert(isValidPaper(final), 'artifact remains 001-valid after threading 001→002→003→004→005→003');
		assert(final.abstract === 'End-to-end Revised Abstract', 'newer revision content applied at the tail');
		assert(final.citationCount === 21 && final.citationsKnown === true, 'refreshed (now cited) citation count read back through 003');
		assert(final.publicationYear === YEAR, 'publicationYear (the 002/005 window key) stayed stable across the whole chain');
		assert(eqArr(final.embedding, computeBaselineEmbedding('Head Title', 'End-to-end Revised Abstract').embedding), 'embedding stayed consistent with 002 computation after content change');
		body = await managedBodyOf(fs, SID);
		assert(body.includes('End-to-end Revised Abstract'), 'the 004 summary was REGENERATED over the refreshed abstract (004→005→003)');
		assert(!body.includes('Head Abstract'), 'the stale collection-time summary was replaced');
		assert(!body.includes('## Future directions'), 'the paper is now cited (21) → the Future directions section is gone after regeneration');
		assert((await fs.read(mdPath))!.includes('USER TAIL'), 'user-owned note region untouched across the entire five-spec pipeline');
	});

	skip('E2', '[system] LLM/local-transformer canonical embedding threaded through collection + refresh', 'the non-bundled canonical embedding provider (002 FR-045/FR-046) is env-gated and stubbed (upgradeEmbedding/computeCanonicalEmbedding return the baseline while the model is absent); the whole chain is exercised on the bundled canonical provider by E1');

	const p = results.filter((r) => r.status === 'PASS').length;
	const f = results.filter((r) => r.status === 'FAIL').length;
	const s = results.filter((r) => r.status === 'SKIP').length;
	console.log(`\nSummary: ${p} passed, ${f} failed, ${s} skipped`);
	process.exitCode = f > 0 ? 1 : 0;
}
main().catch((e) => { console.error('HARNESS ERROR', e); process.exitCode = 1; });
